//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/integration/ExternalStorage.java
//
//  Created by polar on 5/25/13.
//

@class JavaIoFile;

#import "JreEmulation.h"

@interface ComAdironBusmeIntegrationExternalStorage : NSObject {
}

+ (BOOL)isExternalStorageAvailable;
+ (BOOL)isExternalStorageWriteable;
+ (JavaIoFile *)getExternalStorageDirectory;
- (id)init;
@end
