//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/integration/GeoPoint.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmeIntegrationLocation;

#import "JreEmulation.h"
#import "java/io/Serializable.h"
#import "org/osmdroid/api/IGeoPoint.h"
#import "org/osmdroid/util/constants/GeoConstants.h"

#define ComAdironBusmeIntegrationGeoPoint_DEG2RAD 0.17453292
#define ComAdironBusmeIntegrationGeoPoint_serialVersionUID 1

@interface ComAdironBusmeIntegrationGeoPoint : NSObject < OrgOsmdroidApiIGeoPoint, OrgOsmdroidUtilConstantsGeoConstants, JavaIoSerializable, NSCopying > {
 @public
  int mLongitudeE6_;
  int mLatitudeE6_;
  int mAltitude_;
}

@property (nonatomic, assign) int mLongitudeE6;
@property (nonatomic, assign) int mLatitudeE6;
@property (nonatomic, assign) int mAltitude;

+ (float)DEG2RAD;
+ (long long int)serialVersionUID;
- (id)initWithInt:(int)aLatitudeE6
          withInt:(int)aLongitudeE6;
- (id)initWithInt:(int)aLatitudeE6
          withInt:(int)aLongitudeE6
          withInt:(int)aAltitude;
- (id)initWithDouble:(double)aLatitude
          withDouble:(double)aLongitude;
- (id)initWithDouble:(double)aLatitude
          withDouble:(double)aLongitude
          withDouble:(double)aAltitude;
- (id)initWithComAdironBusmeIntegrationLocation:(ComAdironBusmeIntegrationLocation *)aLocation;
- (id)initWithComAdironBusmeIntegrationGeoPoint:(ComAdironBusmeIntegrationGeoPoint *)aGeopoint;
+ (ComAdironBusmeIntegrationGeoPoint *)fromDoubleStringWithNSString:(NSString *)s
                                                        withUnichar:(unichar)spacer;
+ (ComAdironBusmeIntegrationGeoPoint *)fromInvertedDoubleStringWithNSString:(NSString *)s
                                                                withUnichar:(unichar)spacer;
+ (ComAdironBusmeIntegrationGeoPoint *)fromIntStringWithNSString:(NSString *)s;
- (int)getLongitudeE6;
- (int)getLatitudeE6;
- (int)getAltitude;
- (void)setLongitudeE6WithInt:(int)aLongitudeE6;
- (void)setLatitudeE6WithInt:(int)aLatitudeE6;
- (void)setAltitudeWithInt:(int)aAltitude;
- (void)setCoordsE6WithInt:(int)aLatitudeE6
                   withInt:(int)aLongitudeE6;
- (id)clone;
- (NSString *)description;
- (BOOL)isEqual:(id)obj;
- (NSUInteger)hash;
- (int)distanceToWithOrgOsmdroidApiIGeoPoint:(id<OrgOsmdroidApiIGeoPoint>)other;
- (double)bearingToWithOrgOsmdroidApiIGeoPoint:(id<OrgOsmdroidApiIGeoPoint>)other;
- (ComAdironBusmeIntegrationGeoPoint *)destinationPointWithDouble:(double)aDistanceInMeters
                                                        withFloat:(float)aBearingInDegrees;
+ (ComAdironBusmeIntegrationGeoPoint *)fromCenterBetweenWithComAdironBusmeIntegrationGeoPoint:(ComAdironBusmeIntegrationGeoPoint *)geoPointA
                                                        withComAdironBusmeIntegrationGeoPoint:(ComAdironBusmeIntegrationGeoPoint *)geoPointB;
- (NSString *)toDoubleString;
- (NSString *)toInvertedDoubleString;
- (id)copyWithZone:(NSZone *)zone;
@end
