//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/integration/Handler.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/integration/Handler.h"
#import "com/adiron/busme/platform/Handler.h"
#import "java/lang/Runnable.h"

@implementation ComAdironBusmeIntegrationHandler

- (ComAdironBusmePlatformHandler *)delegate {
  return delegate_;
}
- (void)setDelegate:(ComAdironBusmePlatformHandler *)delegate {
  JreOperatorRetainedAssign(&delegate_, delegate);
}
@synthesize delegate = delegate_;

- (BOOL)postWithJavaLangRunnable:(id<JavaLangRunnable>)r {
  return [((ComAdironBusmePlatformHandler *) NIL_CHK(delegate_)) postWithJavaLangRunnable:r];
}

- (BOOL)postAtFrontOfQueueWithJavaLangRunnable:(id<JavaLangRunnable>)r {
  return [((ComAdironBusmePlatformHandler *) NIL_CHK(delegate_)) postAtFrontOfQueueWithJavaLangRunnable:r];
}

- (BOOL)postDelayedWithJavaLangRunnable:(id<JavaLangRunnable>)r
                            withLongInt:(long long int)delayMillis {
  return [((ComAdironBusmePlatformHandler *) NIL_CHK(delegate_)) postDelayedWithJavaLangRunnable:r withLongInt:delayMillis];
}

- (void)removeCallbacksWithJavaLangRunnable:(id<JavaLangRunnable>)r
                                     withId:(id)token {
  [((ComAdironBusmePlatformHandler *) NIL_CHK(delegate_)) removeCallbacksWithJavaLangRunnable:r withId:token];
}

- (void)removeCallbacksWithJavaLangRunnable:(id<JavaLangRunnable>)r {
  [((ComAdironBusmePlatformHandler *) NIL_CHK(delegate_)) removeCallbacksWithJavaLangRunnable:r];
}

- (id)init {
  return [super init];
}

- (void)dealloc {
  JreOperatorRetainedAssign(&delegate_, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmeIntegrationHandler *typedCopy = (ComAdironBusmeIntegrationHandler *) copy;
  typedCopy.delegate = delegate_;
}

@end
