//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/integration/LocationManager.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/integration/LocationManager.h"

@implementation ComAdironBusmeIntegrationLocationManager

static NSString * ComAdironBusmeIntegrationLocationManager_GPS_PROVIDER_ = @"gps";

+ (NSString *)GPS_PROVIDER {
  return ComAdironBusmeIntegrationLocationManager_GPS_PROVIDER_;
}

- (id)init {
  return [super init];
}

- (void)dealloc {
  [super dealloc];
}

@end
