//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/integration/Location.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/integration/Location.h"

@implementation ComAdironBusmeIntegrationLocation

@synthesize accuracy = accuracy_;
@synthesize altitude = altitude_;
@synthesize bearing = bearing_;
@synthesize latitude = latitude_;
@synthesize longitude = longitude_;
- (NSString *)provider {
  return provider_;
}
- (void)setProvider:(NSString *)provider {
  JreOperatorRetainedAssign(&provider_, provider);
}
@synthesize provider = provider_;
@synthesize speed = speed_;
@synthesize time = time_;
@synthesize hasAccuracy_ = hasAccuracy__;
@synthesize hasAltitude_ = hasAltitude__;
@synthesize hasBearing_ = hasBearing__;
@synthesize hasSpeed_ = hasSpeed__;

- (id)initWithNSString:(NSString *)name {
  return [super init];
}

- (float)bearingToWithComAdironBusmeIntegrationLocation:(ComAdironBusmeIntegrationLocation *)dest {
  return 0;
}

- (int)describeContents {
  return 0;
}

- (float)distanceToWithComAdironBusmeIntegrationLocation:(ComAdironBusmeIntegrationLocation *)dest {
  return 0;
}

- (BOOL)isEqual:(id)o {
  return NO;
}

- (float)getAccuracy {
  return accuracy_;
}

- (double)getAltitude {
  return altitude_;
}

- (float)getBearing {
  return bearing_;
}

- (double)getLatitude {
  return latitude_;
}

- (double)getLongitude {
  return longitude_;
}

- (NSString *)getProvider {
  return provider_;
}

- (float)getSpeed {
  return speed_;
}

- (long long int)getTime {
  return time_;
}

- (BOOL)hasAccuracy {
  return hasAccuracy__;
}

- (BOOL)hasAltitude {
  return hasAltitude__;
}

- (BOOL)hasBearing {
  return hasBearing__;
}

- (BOOL)hasSpeed {
  return hasSpeed__;
}

- (void)removeAccuracy {
  hasAccuracy__ = NO;
}

- (void)removeAltitude {
  hasAltitude__ = NO;
}

- (void)removeBearing {
  hasBearing__ = NO;
}

- (void)removeSpeed {
  hasSpeed__ = NO;
}

- (void)reset {
}

- (void)setWithComAdironBusmeIntegrationLocation:(ComAdironBusmeIntegrationLocation *)l {
}

- (void)setAccuracyWithFloat:(float)accuracy {
  self.accuracy = accuracy;
}

- (void)setAltitudeWithDouble:(double)altitude {
  self.altitude = altitude;
}

- (void)setBearingWithFloat:(float)bearing {
  self.bearing = bearing;
}

- (void)setLatitudeWithDouble:(double)latitude {
  self.latitude = latitude;
}

- (void)setLongitudeWithDouble:(double)longitude {
  self.longitude = longitude;
}

- (void)setProviderWithNSString:(NSString *)provider {
  self.provider = provider;
}

- (void)setSpeedWithFloat:(float)speed {
  self.speed = speed;
}

- (void)setTimeWithLongInt:(long long int)time {
  self.time = time;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&provider_, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmeIntegrationLocation *typedCopy = (ComAdironBusmeIntegrationLocation *) copy;
  typedCopy.accuracy = accuracy_;
  typedCopy.altitude = altitude_;
  typedCopy.bearing = bearing_;
  typedCopy.latitude = latitude_;
  typedCopy.longitude = longitude_;
  typedCopy.provider = provider_;
  typedCopy.speed = speed_;
  typedCopy.time = time_;
  typedCopy.hasAccuracy_ = hasAccuracy__;
  typedCopy.hasAltitude_ = hasAltitude__;
  typedCopy.hasBearing_ = hasBearing__;
  typedCopy.hasSpeed_ = hasSpeed__;
}

@end
