//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/integration/LocationManager.java
//
//  Created by polar on 5/25/13.
//

#import "JreEmulation.h"

@interface ComAdironBusmeIntegrationLocationManager : NSObject {
}

+ (NSString *)GPS_PROVIDER;
- (id)init;
@end
