//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/integration/LocationListenerDelegate.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmePlatformLocation;
@class ComAdironBusmePlatformLocationListenerDelegate;

#import "JreEmulation.h"

@interface ComAdironBusmeIntegrationLocationListenerDelegate : NSObject {
 @public
  ComAdironBusmePlatformLocationListenerDelegate *delegate_;
}

@property (nonatomic, retain) ComAdironBusmePlatformLocationListenerDelegate *delegate;

- (BOOL)isEqual:(id)o;
- (NSUInteger)hash;
- (void)onLocationChangedWithComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)location;
- (void)onProviderDisabledWithNSString:(NSString *)provider;
- (void)onProviderEnabledWithNSString:(NSString *)provider;
- (void)onStatusChangedWithNSString:(NSString *)provider
                            withInt:(int)status;
- (NSString *)description;
- (id)init;
@end
