//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/integration/Log.java
//
//  Created by polar on 5/25/13.
//

@class IOSObjectArray;
@class JavaLangThrowable;
@class JavaUtilLoggingLogger;

#import "JreEmulation.h"

@interface ComAdironBusmeIntegrationLog : NSObject {
}

+ (JavaUtilLoggingLogger *)logger;
+ (void)setLogger:(JavaUtilLoggingLogger *)logger;
+ (ComAdironBusmeIntegrationLog *)newInstance OBJC_METHOD_FAMILY_NONE;
- (void)dWithNSString:(NSString *)tag
         withNSString:(NSString *)message;
- (void)dWithNSString:(NSString *)tag
         withNSString:(NSString *)message
withJavaLangThrowable:(JavaLangThrowable *)e;
- (void)eWithNSString:(NSString *)tag
         withNSString:(NSString *)message;
- (void)eWithNSString:(NSString *)tag
         withNSString:(NSString *)message
withJavaLangThrowable:(JavaLangThrowable *)e;
- (void)iWithNSString:(NSString *)tag
         withNSString:(NSString *)message;
- (void)iWithNSString:(NSString *)tag
         withNSString:(NSString *)message
withJavaLangThrowable:(JavaLangThrowable *)e;
- (void)vWithNSString:(NSString *)tag
         withNSString:(NSString *)message;
- (void)vWithNSString:(NSString *)tag
         withNSString:(NSString *)message
withJavaLangThrowable:(JavaLangThrowable *)e;
- (void)wtfWithNSString:(NSString *)tag
           withNSString:(NSString *)message;
+ (void)wtfWithNSString:(NSString *)tag
           withNSString:(NSString *)message
  withJavaLangThrowable:(JavaLangThrowable *)e;
- (void)ddWithNSString:(NSString *)tag
          withNSString:(NSString *)format
     withNSObjectArray:(IOSObjectArray *)args;
- (void)eeWithNSString:(NSString *)tag
          withNSString:(NSString *)format
     withNSObjectArray:(IOSObjectArray *)args;
- (void)iiWithNSString:(NSString *)tag
          withNSString:(NSString *)format
     withNSObjectArray:(IOSObjectArray *)args;
- (void)vvWithNSString:(NSString *)tag
          withNSString:(NSString *)format
     withNSObjectArray:(IOSObjectArray *)args;
- (id)init;
@end
