//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/api/APIBase.java
//
//  Created by polar on 5/25/13.
//

#import "IOSClass.h"
#import "IOSObjectArray.h"
#import "com/adiron/busme/api/APIBase.h"
#import "com/adiron/busme/integration/http/HttpEntity.h"
#import "com/adiron/busme/integration/http/HttpResponse.h"
#import "com/adiron/busme/integration/http/MyHttpClient.h"
#import "com/adiron/busme/platform/Log.h"
#import "java/io/BufferedReader.h"
#import "java/io/InputStream.h"
#import "java/io/InputStreamReader.h"
#import "java/io/PrintWriter.h"
#import "java/io/StringWriter.h"
#import "java/lang/Exception.h"
#import "java/lang/StringBuilder.h"
#import "java/util/ArrayList.h"
#import "java/util/HashMap.h"
#import "java/util/Iterator.h"
#import "java/util/List.h"
#import "java/util/Map.h"
#import "java/util/Set.h"
#import "java/util/Stack.h"
#import "org/xmlpull/v1/XmlPullParser.h"
#import "org/xmlpull/v1/XmlPullParserException.h"
#import "org/xmlpull/v1/XmlPullParserFactory.h"

@implementation ComAdironBusmeApiAPIBase

static NSString * ComAdironBusmeApiAPIBase_LOGTAG_;

- (ComAdironBusmeIntegrationHttpMyHttpClient *)myHttpClient {
  return myHttpClient_;
}
- (void)setMyHttpClient:(ComAdironBusmeIntegrationHttpMyHttpClient *)myHttpClient {
  JreOperatorRetainedAssign(&myHttpClient_, myHttpClient);
}
@synthesize myHttpClient = myHttpClient_;
- (NSString *)csrfParam {
  return csrfParam_;
}
- (void)setCsrfParam:(NSString *)csrfParam {
  JreOperatorRetainedAssign(&csrfParam_, csrfParam);
}
@synthesize csrfParam = csrfParam_;
- (NSString *)csrfToken {
  return csrfToken_;
}
- (void)setCsrfToken:(NSString *)csrfToken {
  JreOperatorRetainedAssign(&csrfToken_, csrfToken);
}
@synthesize csrfToken = csrfToken_;
- (NSString *)masterParam {
  return masterParam_;
}
- (void)setMasterParam:(NSString *)masterParam {
  JreOperatorRetainedAssign(&masterParam_, masterParam);
}
@synthesize masterParam = masterParam_;
- (NSString *)masterToken {
  return masterToken_;
}
- (void)setMasterToken:(NSString *)masterToken {
  JreOperatorRetainedAssign(&masterToken_, masterToken);
}
@synthesize masterToken = masterToken_;

+ (NSString *)LOGTAG {
  return ComAdironBusmeApiAPIBase_LOGTAG_;
}

- (ComAdironBusmeIntegrationHttpHttpEntity *)openURLWithNSString:(NSString *)url {
  return [((ComAdironBusmeIntegrationHttpMyHttpClient *) NIL_CHK(myHttpClient_)) openURLWithNSString:url];
}

- (ComAdironBusmeIntegrationHttpHttpResponse *)getURLResponseWithNSString:(NSString *)url {
  return [((ComAdironBusmeIntegrationHttpMyHttpClient *) NIL_CHK(myHttpClient_)) getURLResponseWithNSString:url];
}

- (ComAdironBusmeIntegrationHttpHttpEntity *)postURLWithNSString:(NSString *)url
                                                withJavaUtilList:(id<JavaUtilList>)params {
  return [((ComAdironBusmeIntegrationHttpMyHttpClient *) NIL_CHK(myHttpClient_)) postURLWithNSString:url withJavaUtilList:params];
}

- (ComAdironBusmeIntegrationHttpHttpResponse *)postURLResponseWithNSString:(NSString *)url
                                                          withJavaUtilList:(id<JavaUtilList>)params {
  return [((ComAdironBusmeIntegrationHttpMyHttpClient *) NIL_CHK(myHttpClient_)) postURLResponseWithNSString:url withJavaUtilList:params];
}

- (ComAdironBusmeIntegrationHttpHttpEntity *)postDeleteURLWithNSString:(NSString *)url {
  return [((ComAdironBusmeIntegrationHttpMyHttpClient *) NIL_CHK(myHttpClient_)) postDeleteURLWithNSString:url];
}

- (id)init {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&myHttpClient_, [[[ComAdironBusmeIntegrationHttpMyHttpClient alloc] init] autorelease]);
  }
  return self;
}

- (NSString *)convertStreamToStringWithJavaIoInputStream:(JavaIoInputStream *)inArg {
  JavaIoBufferedReader *reader = [[[JavaIoBufferedReader alloc] initWithJavaIoReader:[[[JavaIoInputStreamReader alloc] initWithJavaIoInputStream:inArg] autorelease]] autorelease];
  JavaLangStringBuilder *sb = [[[JavaLangStringBuilder alloc] init] autorelease];
  NSString *line = nil;
  @try {
    line = [((JavaIoBufferedReader *) NIL_CHK(reader)) readLine];
    while (line != nil) {
      [((JavaLangStringBuilder *) NIL_CHK(sb)) appendWithNSString:line];
      line = [((JavaIoBufferedReader *) NIL_CHK(reader)) readLine];
      if (line != nil) {
        [((JavaLangStringBuilder *) NIL_CHK(sb)) appendWithNSString:@"\n"];
      }
    }
  }
  @finally {
    [((JavaIoBufferedReader *) NIL_CHK(reader)) close];
  }
  [ComAdironBusmePlatformLog dWithNSString:ComAdironBusmeApiAPIBase_LOGTAG_ withNSString:[NSString stringWithFormat:@"Got %@", sb]];
  return [((JavaLangStringBuilder *) NIL_CHK(sb)) description];
}

- (ComAdironBusmeApiAPIBase_Tag *)xmlParseWithJavaIoInputStream:(JavaIoInputStream *)myData {
  @try {
    id<OrgXmlpullV1XmlPullParser> parser = [[OrgXmlpullV1XmlPullParserFactory newInstance] newPullParser];
    [((id<OrgXmlpullV1XmlPullParser>) NIL_CHK(parser)) setInputWithJavaIoReader:[[[JavaIoInputStreamReader alloc] initWithJavaIoInputStream:myData] autorelease]];
    int eventType = [((id<OrgXmlpullV1XmlPullParser>) NIL_CHK(parser)) getEventType];
    JavaUtilStack *stack = [[[JavaUtilStack alloc] init] autorelease];
    [((JavaUtilStack *) NIL_CHK(stack)) pushWithId:[[[ComAdironBusmeApiAPIBase_Tag alloc] initWithComAdironBusmeApiAPIBase:self] autorelease]];
    while (eventType != OrgXmlpullV1XmlPullParser_END_DOCUMENT) {
      if (eventType == OrgXmlpullV1XmlPullParser_START_TAG) {
        ComAdironBusmeApiAPIBase_Tag *parent = ((ComAdironBusmeApiAPIBase_Tag *) [((JavaUtilStack *) NIL_CHK(stack)) peek]);
        ComAdironBusmeApiAPIBase_Tag *tag = [[[ComAdironBusmeApiAPIBase_Tag alloc] initWithComAdironBusmeApiAPIBase:self] autorelease];
        [((id<JavaUtilList>) NIL_CHK(parent.childNodes)) addWithId:tag];
        [((JavaUtilStack *) NIL_CHK(stack)) pushWithId:tag];
        ((ComAdironBusmeApiAPIBase_Tag *) NIL_CHK(tag)).name = [((id<OrgXmlpullV1XmlPullParser>) NIL_CHK(parser)) getName];
        int len = [((id<OrgXmlpullV1XmlPullParser>) NIL_CHK(parser)) getAttributeCount];
        for (int i = 0; i < len; i++) {
          [((id<JavaUtilMap>) NIL_CHK(tag.attributes)) putWithId:[((id<OrgXmlpullV1XmlPullParser>) NIL_CHK(parser)) getAttributeNameWithInt:i] withId:[((id<OrgXmlpullV1XmlPullParser>) NIL_CHK(parser)) getAttributeValueWithInt:i]];
        }
        eventType = [((id<OrgXmlpullV1XmlPullParser>) NIL_CHK(parser)) next];
      }
      else if (eventType == OrgXmlpullV1XmlPullParser_TEXT) {
        ComAdironBusmeApiAPIBase_Tag *parent = ((ComAdironBusmeApiAPIBase_Tag *) [((JavaUtilStack *) NIL_CHK(stack)) peek]);
        ((ComAdironBusmeApiAPIBase_Tag *) NIL_CHK(parent)).text = [((id<OrgXmlpullV1XmlPullParser>) NIL_CHK(parser)) getText];
        eventType = [((id<OrgXmlpullV1XmlPullParser>) NIL_CHK(parser)) next];
      }
      else if (eventType == OrgXmlpullV1XmlPullParser_END_TAG) {
        ComAdironBusmeApiAPIBase_Tag *tag = ((ComAdironBusmeApiAPIBase_Tag *) [((JavaUtilStack *) NIL_CHK(stack)) pop]);
        eventType = [((id<OrgXmlpullV1XmlPullParser>) NIL_CHK(parser)) next];
      }
      else {
        @try {
          eventType = [((id<OrgXmlpullV1XmlPullParser>) NIL_CHK(parser)) next];
        }
        @catch (OrgXmlpullV1XmlPullParserException *e) {
          [ComAdironBusmePlatformLog dWithNSString:ComAdironBusmeApiAPIBase_LOGTAG_ withNSString:[NSString stringWithFormat:@"exception = %d message %@", eventType, [((OrgXmlpullV1XmlPullParserException *) NIL_CHK(e)) getMessage]]];
          @throw e;
        }
      }
    }
    ComAdironBusmeApiAPIBase_Tag *result = ((ComAdironBusmeApiAPIBase_Tag *) [((JavaUtilStack *) NIL_CHK(stack)) pop]);
    if (result != nil && ((ComAdironBusmeApiAPIBase_Tag *) NIL_CHK(result)).childNodes != nil && [((id<JavaUtilList>) NIL_CHK(result.childNodes)) size] > 0) {
      return ((ComAdironBusmeApiAPIBase_Tag *) [((id<JavaUtilList>) NIL_CHK(result.childNodes)) getWithInt:0]);
    }
    return nil;
  }
  @catch (JavaLangException *e) {
    [ComAdironBusmePlatformLog dWithNSString:ComAdironBusmeApiAPIBase_LOGTAG_ withNSString:[NSString stringWithFormat:@"IOError: quite possibly EOF? %@", [((JavaLangException *) NIL_CHK(e)) getMessage]]];
    [((JavaLangException *) NIL_CHK(e)) printStackTrace];
  }
  return nil;
}

- (ComAdironBusmeApiAPIBase_Tag *)xmlParseWithComAdironBusmeIntegrationHttpHttpEntity:(ComAdironBusmeIntegrationHttpHttpEntity *)ent {
  ComAdironBusmeApiAPIBase_Tag *tag = nil;
  if (ent != nil) {
    @try {
      JavaIoInputStream *in = [ent getContent];
      tag = [self xmlParseWithJavaIoInputStream:in];
      [ent consumeContent];
      return tag;
    }
    @finally {
      [ent consumeContent];
    }
  }
  return tag;
}

+ (void)initialize {
  if (self == [ComAdironBusmeApiAPIBase class]) {
    JreOperatorRetainedAssign(&ComAdironBusmeApiAPIBase_LOGTAG_, [[IOSClass classWithClass:[ComAdironBusmeApiAPIBase class]] getName]);
  }
}

- (void)dealloc {
  JreOperatorRetainedAssign(&masterToken_, nil);
  JreOperatorRetainedAssign(&masterParam_, nil);
  JreOperatorRetainedAssign(&csrfToken_, nil);
  JreOperatorRetainedAssign(&csrfParam_, nil);
  JreOperatorRetainedAssign(&myHttpClient_, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmeApiAPIBase *typedCopy = (ComAdironBusmeApiAPIBase *) copy;
  typedCopy.myHttpClient = myHttpClient_;
  typedCopy.csrfParam = csrfParam_;
  typedCopy.csrfToken = csrfToken_;
  typedCopy.masterParam = masterParam_;
  typedCopy.masterToken = masterToken_;
}

@end
@implementation ComAdironBusmeApiAPIBase_Tag

- (NSString *)name {
  return name_;
}
- (void)setName:(NSString *)name {
  JreOperatorRetainedAssign(&name_, name);
}
@synthesize name = name_;
- (id<JavaUtilMap>)attributes {
  return attributes_;
}
- (void)setAttributes:(id<JavaUtilMap>)attributes {
  JreOperatorRetainedAssign(&attributes_, attributes);
}
@synthesize attributes = attributes_;
- (NSString *)text {
  return text_;
}
- (void)setText:(NSString *)text {
  JreOperatorRetainedAssign(&text_, text);
}
@synthesize text = text_;
- (id<JavaUtilList>)childNodes {
  return childNodes_;
}
- (void)setChildNodes:(id<JavaUtilList>)childNodes {
  JreOperatorRetainedAssign(&childNodes_, childNodes);
}
@synthesize childNodes = childNodes_;

- (void)printWithJavaIoPrintWriter:(JavaIoPrintWriter *)outArg {
  [((JavaIoPrintWriter *) NIL_CHK(outArg)) printWithNSString:[NSString stringWithFormat:@"<%@ " , name_, nil]];
  {
    id<JavaUtilIterator> iter__ = ((id<JavaUtilIterator>) [((id<JavaUtilSet>) [((id<JavaUtilMap>) NIL_CHK(attributes_)) keySet]) iterator]);
    while ([((id<JavaUtilIterator>) NIL_CHK(iter__)) hasNext]) {
      NSString *key = ((NSString *) [((id<JavaUtilIterator>) NIL_CHK(iter__)) next]);
      [((JavaIoPrintWriter *) NIL_CHK(outArg)) printWithNSString:[NSString stringWithFormat:@"%@=%@ " , key, ((NSString *) [((id<JavaUtilMap>) NIL_CHK(attributes_)) getWithId:key]), nil]];
    }
  }
  [((JavaIoPrintWriter *) NIL_CHK(outArg)) printWithNSString:@">\n"];
  {
    id<JavaUtilIterator> iter__ = ((id<JavaUtilIterator>) [((id<JavaUtilList>) NIL_CHK(childNodes_)) iterator]);
    while ([((id<JavaUtilIterator>) NIL_CHK(iter__)) hasNext]) {
      ComAdironBusmeApiAPIBase_Tag *tag = ((ComAdironBusmeApiAPIBase_Tag *) [((id<JavaUtilIterator>) NIL_CHK(iter__)) next]);
      [((ComAdironBusmeApiAPIBase_Tag *) NIL_CHK(tag)) printWithJavaIoPrintWriter:outArg];
    }
  }
  [((JavaIoPrintWriter *) NIL_CHK(outArg)) printWithNSString:[NSString stringWithFormat:@"</%@>\n" , name_, nil]];
}

- (NSString *)description {
  JavaIoStringWriter *sout = [[[JavaIoStringWriter alloc] init] autorelease];
  JavaIoPrintWriter *out = [[[JavaIoPrintWriter alloc] initWithJavaIoWriter:sout] autorelease];
  [self printWithJavaIoPrintWriter:out];
  return [((JavaIoStringWriter *) NIL_CHK(sout)) description];
}

- (id)initWithComAdironBusmeApiAPIBase:(ComAdironBusmeApiAPIBase *)outer$ {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&attributes_, [[[JavaUtilHashMap alloc] init] autorelease]);
    JreOperatorRetainedAssign(&childNodes_, [[[JavaUtilArrayList alloc] init] autorelease]);
  }
  return self;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&childNodes_, nil);
  JreOperatorRetainedAssign(&text_, nil);
  JreOperatorRetainedAssign(&attributes_, nil);
  JreOperatorRetainedAssign(&name_, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmeApiAPIBase_Tag *typedCopy = (ComAdironBusmeApiAPIBase_Tag *) copy;
  typedCopy.name = name_;
  typedCopy.attributes = attributes_;
  typedCopy.text = text_;
  typedCopy.childNodes = childNodes_;
}

@end
