//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/api/BannerInfo.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmeIntegrationGeoPoint;

#import "JreEmulation.h"

@interface ComAdironBusmeApiBannerInfo : NSObject {
 @public
  NSString *id__;
  ComAdironBusmeIntegrationGeoPoint *point_;
  int version__;
  int length_;
  int frequency_;
  long long int radius_;
  int priority_;
  long long int expiryTime_;
  NSString *title_;
  NSString *description__;
  NSString *goUrl_;
  NSString *iconUrl_;
  BOOL seen_;
  long long int lastSeen_;
}

@property (nonatomic, copy) NSString *id_;
@property (nonatomic, retain) ComAdironBusmeIntegrationGeoPoint *point;
@property (nonatomic, assign) int version_;
@property (nonatomic, assign) int length;
@property (nonatomic, assign) int frequency;
@property (nonatomic, assign) long long int radius;
@property (nonatomic, assign) int priority;
@property (nonatomic, assign) long long int expiryTime;
@property (nonatomic, copy) NSString *title;
@property (nonatomic, copy) NSString *description_;
@property (nonatomic, copy) NSString *goUrl;
@property (nonatomic, copy) NSString *iconUrl;
@property (nonatomic, assign) BOOL seen;
@property (nonatomic, assign) long long int lastSeen;

- (BOOL)shouldBeSeenWithLongInt:(long long int)time;
- (long long int)nextTimeWithLongInt:(long long int)now;
- (ComAdironBusmeIntegrationGeoPoint *)getPoint;
- (int)getFrequency;
- (void)setFrequencyWithInt:(int)frequency;
- (int)getPriority;
- (void)setPriorityWithInt:(int)priority;
- (long long int)getExpiryTime;
- (void)setExpiryTimeWithLongInt:(long long int)expiryTime;
- (long long int)getLastSeen;
- (void)setLastSeenNow;
- (void)setLastSeenWithLongInt:(long long int)lastSeen;
- (NSString *)getId;
- (void)setIdWithNSString:(NSString *)id_;
- (int)getVersion;
- (void)setVersionWithInt:(int)version_;
- (long long int)getRadius;
- (void)setRadiusWithLongInt:(long long int)radius;
- (NSString *)getTitle;
- (void)setTitleWithNSString:(NSString *)title;
- (NSString *)getDescription;
- (void)setDescriptionWithNSString:(NSString *)description_;
- (NSString *)getGoUrl;
- (void)setGoUrlWithNSString:(NSString *)goUrl;
- (NSString *)getIconUrl;
- (void)setIconUrlWithNSString:(NSString *)iconUrl;
- (BOOL)isSeen;
- (void)setSeenWithBOOL:(BOOL)seen;
- (void)setPointWithComAdironBusmeIntegrationGeoPoint:(ComAdironBusmeIntegrationGeoPoint *)point;
- (BOOL)isDisplayTimeExpiredWithLongInt:(long long int)time;
- (int)getLength;
- (id)init;
@end
