//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/api/BuspassAPI.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmeApiBuspass;
@class ComAdironBusmeApiBuspassAPI_Login;
@class ComAdironBusmeIntegrationBoundingBoxE6;
@protocol JavaUtilList;

#import "JreEmulation.h"
#import "com/adiron/busme/api/APIBase.h"

@interface ComAdironBusmeApiBuspassAPI : ComAdironBusmeApiAPIBase {
 @public
  NSString *apiUrl_;
  NSString *appVersion_;
  NSString *platform_;
  ComAdironBusmeApiBuspass *buspass_;
  BOOL ready_;
  int postlocTimeRate_;
  int postlocDistRate_;
  int curlocTimeRate_;
  int updateRate_;
  int activeStartDisplayThreshold_;
  int activeEndWaitThreshold_;
  double offRouteDistanceThreshold_;
  int offRouteCountThreshold_;
  double offRouteTimeThreshold_;
  int syncRate_;
  long long int bannerMaxImageSize_;
  long long int bannerRefreshRate_;
}

@property (nonatomic, copy) NSString *apiUrl;
@property (nonatomic, copy) NSString *appVersion;
@property (nonatomic, copy) NSString *platform;
@property (nonatomic, retain) ComAdironBusmeApiBuspass *buspass;
@property (nonatomic, assign) BOOL ready;
@property (nonatomic, assign) int postlocTimeRate;
@property (nonatomic, assign) int postlocDistRate;
@property (nonatomic, assign) int curlocTimeRate;
@property (nonatomic, assign) int updateRate;
@property (nonatomic, assign) int activeStartDisplayThreshold;
@property (nonatomic, assign) int activeEndWaitThreshold;
@property (nonatomic, assign) double offRouteDistanceThreshold;
@property (nonatomic, assign) int offRouteCountThreshold;
@property (nonatomic, assign) double offRouteTimeThreshold;
@property (nonatomic, assign) int syncRate;
@property (nonatomic, assign) long long int bannerMaxImageSize;
@property (nonatomic, assign) long long int bannerRefreshRate;

+ (NSString *)LOGTAG;
- (id)initWithNSString:(NSString *)initialUrl
          withNSString:(NSString *)platform
          withNSString:(NSString *)appVersion;
- (BOOL)isReady;
- (NSString *)getApiUrl;
- (void)setApiUrlWithNSString:(NSString *)apiUrl;
- (NSString *)getPlatformName;
- (NSString *)getPlatformArgs;
- (NSString *)getBusmeAppVersionString;
- (ComAdironBusmeApiBuspass *)get;
- (ComAdironBusmeApiBuspass *)forceGet;
- (NSString *)getVersion;
- (NSString *)getMode;
- (NSString *)getName;
- (NSString *)getSlug;
- (NSString *)getAuthUrl;
- (NSString *)getLoginUrl;
- (NSString *)getRegisterUrl;
- (NSString *)getLogoutUrl;
- (NSString *)getOauthLoginUrl;
- (NSString *)getOauthLogoutUrl;
- (NSString *)getBannerImageUrl;
- (void)setPostlocTimeRateWithInt:(int)postlocTimeRate;
- (int)getPostlocTimeRate;
- (int)getPostlocDistRate;
- (void)setPostlocDistRateWithInt:(int)postlocDistRate;
- (int)getCurlocTimeRate;
- (void)setCurlocTimeRateWithInt:(int)curlocTimeRate;
- (NSString *)getLon;
- (NSString *)getLat;
- (NSString *)getTimezone;
- (NSString *)getTimeOffset;
- (NSString *)getDateFormat;
- (NSString *)getRouteJourneyIdsUrl;
- (NSString *)getRouteDefinitionUrl;
- (NSString *)getJourneyLocationUrl;
- (NSString *)getMultipleJourneyLocationsUrl;
- (NSString *)getPostJourneyLocationUrl;
- (NSString *)getMessagesUrl;
- (NSString *)getMessageUrl;
- (NSString *)getMarkersUrl;
- (NSString *)getPostFeedbackUrl;
- (NSString *)getPostUpdateUrl;
- (NSString *)getRouteJourneyIds1Url;
- (NSString *)getMarkerClickThruUrl;
- (NSString *)getMessageClickThruUrl;
- (NSString *)getHelpUrl;
- (NSString *)getBannerClickThruUrl;
- (int)getUpdateRate;
- (void)setUpdateRateWithInt:(int)rate;
- (int)getActiveStartDisplayThreshold;
- (void)setActiveStartDisplayThresholdWithInt:(int)rate;
- (int)getActiveEndWaitThreshold;
- (void)setActiveEndWaitThresholdWithInt:(int)rate;
- (double)getOffRouteDistanceThreshold;
- (int)getOffRouteCountThreshold;
- (double)getOffRouteTimeThreshold;
- (void)setOffRouteDistanceThresholdWithDouble:(double)offRouteDistanceThreshold;
- (void)setOffRouteCountThresholdWithInt:(int)offRouteCountThreshold;
- (void)setOffRouteTimeThresholdWithDouble:(double)offRouteTimeThreshold;
- (int)getSyncRate;
- (void)setSyncRateWithInt:(int)rate;
- (id<JavaUtilList>)getInitialMessages;
- (long long int)getBannerMaxImageSize;
- (void)setBannerMaxImageSizeWithLongInt:(long long int)bannerMaxImageSize;
- (void)setBannerRefreshRateWithLongInt:(long long int)bannerRefreshRate;
- (long long int)getBannerRefreshRate;
- (ComAdironBusmeIntegrationBoundingBoxE6 *)getBoundingBox;
- (void)logout;
- (ComAdironBusmeApiBuspassAPI_Login *)authorizeWithNSString:(NSString *)authUrl
                                                withNSString:(NSString *)roleIntent
                                                withNSString:(NSString *)access_token;
- (ComAdironBusmeApiBuspassAPI_Login *)passwordLoginWithNSString:(NSString *)loginUrl
                                                    withNSString:(NSString *)roleIntent
                                                    withNSString:(NSString *)id_
                                                    withNSString:(NSString *)password;
- (ComAdironBusmeApiBuspassAPI_Login *)passwordRegistrationWithNSString:(NSString *)loginUrl
                                                           withNSString:(NSString *)roleIntent
                                                           withNSString:(NSString *)id_
                                                           withNSString:(NSString *)password
                                                           withNSString:(NSString *)driverAuthCode;
@end

@interface ComAdironBusmeApiBuspassAPI_Login : NSObject {
 @public
  NSString *status_;
  NSString *reason_;
  NSString *name_;
  NSString *email_;
  NSString *driverAuthCode_;
  NSString *roleIntent_;
  NSString *rolesLiteral_;
  id<JavaUtilList> roles_;
  NSString *authToken_;
}

@property (nonatomic, copy) NSString *status;
@property (nonatomic, copy) NSString *reason;
@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSString *email;
@property (nonatomic, copy) NSString *driverAuthCode;
@property (nonatomic, copy) NSString *roleIntent;
@property (nonatomic, copy) NSString *rolesLiteral;
@property (nonatomic, retain) id<JavaUtilList> roles;
@property (nonatomic, copy) NSString *authToken;

- (id)init;
- (id)initWithNSString:(NSString *)status;
- (id)initWithNSString:(NSString *)status
          withNSString:(NSString *)reason;
- (BOOL)hasRoleWithNSString:(NSString *)name;
@end
