//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/api/Buspass.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/api/Buspass.h"
#import "java/util/ArrayList.h"
#import "java/util/List.h"

@implementation ComAdironBusmeApiBuspass

- (NSString *)version_ {
  return version__;
}
- (void)setVersion_:(NSString *)version_ {
  JreOperatorRetainedAssign(&version__, version_);
}
@synthesize version_ = version__;
- (NSString *)mode {
  return mode_;
}
- (void)setMode:(NSString *)mode {
  JreOperatorRetainedAssign(&mode_, mode);
}
@synthesize mode = mode_;
- (NSString *)name {
  return name_;
}
- (void)setName:(NSString *)name {
  JreOperatorRetainedAssign(&name_, name);
}
@synthesize name = name_;
- (NSString *)slug {
  return slug_;
}
- (void)setSlug:(NSString *)slug {
  JreOperatorRetainedAssign(&slug_, slug);
}
@synthesize slug = slug_;
- (NSString *)authUrl {
  return authUrl_;
}
- (void)setAuthUrl:(NSString *)authUrl {
  JreOperatorRetainedAssign(&authUrl_, authUrl);
}
@synthesize authUrl = authUrl_;
- (NSString *)loginUrl {
  return loginUrl_;
}
- (void)setLoginUrl:(NSString *)loginUrl {
  JreOperatorRetainedAssign(&loginUrl_, loginUrl);
}
@synthesize loginUrl = loginUrl_;
- (NSString *)registerUrl {
  return registerUrl_;
}
- (void)setRegisterUrl:(NSString *)registerUrl {
  JreOperatorRetainedAssign(&registerUrl_, registerUrl);
}
@synthesize registerUrl = registerUrl_;
- (NSString *)logoutUrl {
  return logoutUrl_;
}
- (void)setLogoutUrl:(NSString *)logoutUrl {
  JreOperatorRetainedAssign(&logoutUrl_, logoutUrl);
}
@synthesize logoutUrl = logoutUrl_;
- (NSString *)oauthLoginUrl {
  return oauthLoginUrl_;
}
- (void)setOauthLoginUrl:(NSString *)oauthLoginUrl {
  JreOperatorRetainedAssign(&oauthLoginUrl_, oauthLoginUrl);
}
@synthesize oauthLoginUrl = oauthLoginUrl_;
- (NSString *)oauthLogoutUrl {
  return oauthLogoutUrl_;
}
- (void)setOauthLogoutUrl:(NSString *)oauthLogoutUrl {
  JreOperatorRetainedAssign(&oauthLogoutUrl_, oauthLogoutUrl);
}
@synthesize oauthLogoutUrl = oauthLogoutUrl_;
- (NSString *)postloc_time_rate {
  return postloc_time_rate_;
}
- (void)setPostloc_time_rate:(NSString *)postloc_time_rate {
  JreOperatorRetainedAssign(&postloc_time_rate_, postloc_time_rate);
}
@synthesize postloc_time_rate = postloc_time_rate_;
- (NSString *)postloc_dist_rate {
  return postloc_dist_rate_;
}
- (void)setPostloc_dist_rate:(NSString *)postloc_dist_rate {
  JreOperatorRetainedAssign(&postloc_dist_rate_, postloc_dist_rate);
}
@synthesize postloc_dist_rate = postloc_dist_rate_;
- (NSString *)curloc_time_rate {
  return curloc_time_rate_;
}
- (void)setCurloc_time_rate:(NSString *)curloc_time_rate {
  JreOperatorRetainedAssign(&curloc_time_rate_, curloc_time_rate);
}
@synthesize curloc_time_rate = curloc_time_rate_;
- (NSString *)lon {
  return lon_;
}
- (void)setLon:(NSString *)lon {
  JreOperatorRetainedAssign(&lon_, lon);
}
@synthesize lon = lon_;
- (NSString *)lat {
  return lat_;
}
- (void)setLat:(NSString *)lat {
  JreOperatorRetainedAssign(&lat_, lat);
}
@synthesize lat = lat_;
- (NSString *)timezone {
  return timezone_;
}
- (void)setTimezone:(NSString *)timezone {
  JreOperatorRetainedAssign(&timezone_, timezone);
}
@synthesize timezone = timezone_;
- (NSString *)time {
  return time_;
}
- (void)setTime:(NSString *)time {
  JreOperatorRetainedAssign(&time_, time);
}
@synthesize time = time_;
- (NSString *)timeoffset {
  return timeoffset_;
}
- (void)setTimeoffset:(NSString *)timeoffset {
  JreOperatorRetainedAssign(&timeoffset_, timeoffset);
}
@synthesize timeoffset = timeoffset_;
- (NSString *)datefmt {
  return datefmt_;
}
- (void)setDatefmt:(NSString *)datefmt {
  JreOperatorRetainedAssign(&datefmt_, datefmt);
}
@synthesize datefmt = datefmt_;
- (NSString *)getRouteJourneyIdsUrl {
  return getRouteJourneyIdsUrl_;
}
- (void)setGetRouteJourneyIdsUrl:(NSString *)getRouteJourneyIdsUrl {
  JreOperatorRetainedAssign(&getRouteJourneyIdsUrl_, getRouteJourneyIdsUrl);
}
@synthesize getRouteJourneyIdsUrl = getRouteJourneyIdsUrl_;
- (NSString *)getRouteDefinitionUrl {
  return getRouteDefinitionUrl_;
}
- (void)setGetRouteDefinitionUrl:(NSString *)getRouteDefinitionUrl {
  JreOperatorRetainedAssign(&getRouteDefinitionUrl_, getRouteDefinitionUrl);
}
@synthesize getRouteDefinitionUrl = getRouteDefinitionUrl_;
- (NSString *)getJourneyLocationUrl {
  return getJourneyLocationUrl_;
}
- (void)setGetJourneyLocationUrl:(NSString *)getJourneyLocationUrl {
  JreOperatorRetainedAssign(&getJourneyLocationUrl_, getJourneyLocationUrl);
}
@synthesize getJourneyLocationUrl = getJourneyLocationUrl_;
- (NSString *)getMultipleJourneyLocationsUrl {
  return getMultipleJourneyLocationsUrl_;
}
- (void)setGetMultipleJourneyLocationsUrl:(NSString *)getMultipleJourneyLocationsUrl {
  JreOperatorRetainedAssign(&getMultipleJourneyLocationsUrl_, getMultipleJourneyLocationsUrl);
}
@synthesize getMultipleJourneyLocationsUrl = getMultipleJourneyLocationsUrl_;
- (NSString *)postJourneyLocationUrl {
  return postJourneyLocationUrl_;
}
- (void)setPostJourneyLocationUrl:(NSString *)postJourneyLocationUrl {
  JreOperatorRetainedAssign(&postJourneyLocationUrl_, postJourneyLocationUrl);
}
@synthesize postJourneyLocationUrl = postJourneyLocationUrl_;
- (NSString *)getMessageUrl {
  return getMessageUrl_;
}
- (void)setGetMessageUrl:(NSString *)getMessageUrl {
  JreOperatorRetainedAssign(&getMessageUrl_, getMessageUrl);
}
@synthesize getMessageUrl = getMessageUrl_;
- (NSString *)getMessagesUrl {
  return getMessagesUrl_;
}
- (void)setGetMessagesUrl:(NSString *)getMessagesUrl {
  JreOperatorRetainedAssign(&getMessagesUrl_, getMessagesUrl);
}
@synthesize getMessagesUrl = getMessagesUrl_;
- (NSString *)getMarkersUrl {
  return getMarkersUrl_;
}
- (void)setGetMarkersUrl:(NSString *)getMarkersUrl {
  JreOperatorRetainedAssign(&getMarkersUrl_, getMarkersUrl);
}
@synthesize getMarkersUrl = getMarkersUrl_;
- (NSString *)postFeedbackUrl {
  return postFeedbackUrl_;
}
- (void)setPostFeedbackUrl:(NSString *)postFeedbackUrl {
  JreOperatorRetainedAssign(&postFeedbackUrl_, postFeedbackUrl);
}
@synthesize postFeedbackUrl = postFeedbackUrl_;
- (NSString *)updateUrl {
  return updateUrl_;
}
- (void)setUpdateUrl:(NSString *)updateUrl {
  JreOperatorRetainedAssign(&updateUrl_, updateUrl);
}
@synthesize updateUrl = updateUrl_;
- (NSString *)updateRate {
  return updateRate_;
}
- (void)setUpdateRate:(NSString *)updateRate {
  JreOperatorRetainedAssign(&updateRate_, updateRate);
}
@synthesize updateRate = updateRate_;
- (NSString *)activeStartDisplayThreshold {
  return activeStartDisplayThreshold_;
}
- (void)setActiveStartDisplayThreshold:(NSString *)activeStartDisplayThreshold {
  JreOperatorRetainedAssign(&activeStartDisplayThreshold_, activeStartDisplayThreshold);
}
@synthesize activeStartDisplayThreshold = activeStartDisplayThreshold_;
- (NSString *)activeEndWaitThreshold {
  return activeEndWaitThreshold_;
}
- (void)setActiveEndWaitThreshold:(NSString *)activeEndWaitThreshold {
  JreOperatorRetainedAssign(&activeEndWaitThreshold_, activeEndWaitThreshold);
}
@synthesize activeEndWaitThreshold = activeEndWaitThreshold_;
- (NSString *)offRouteDistanceThreshold {
  return offRouteDistanceThreshold_;
}
- (void)setOffRouteDistanceThreshold:(NSString *)offRouteDistanceThreshold {
  JreOperatorRetainedAssign(&offRouteDistanceThreshold_, offRouteDistanceThreshold);
}
@synthesize offRouteDistanceThreshold = offRouteDistanceThreshold_;
- (NSString *)offRouteCountThreshold {
  return offRouteCountThreshold_;
}
- (void)setOffRouteCountThreshold:(NSString *)offRouteCountThreshold {
  JreOperatorRetainedAssign(&offRouteCountThreshold_, offRouteCountThreshold);
}
@synthesize offRouteCountThreshold = offRouteCountThreshold_;
- (NSString *)offRouteTimeThreshold {
  return offRouteTimeThreshold_;
}
- (void)setOffRouteTimeThreshold:(NSString *)offRouteTimeThreshold {
  JreOperatorRetainedAssign(&offRouteTimeThreshold_, offRouteTimeThreshold);
}
@synthesize offRouteTimeThreshold = offRouteTimeThreshold_;
- (NSString *)getRouteJourneyIds1Url {
  return getRouteJourneyIds1Url_;
}
- (void)setGetRouteJourneyIds1Url:(NSString *)getRouteJourneyIds1Url {
  JreOperatorRetainedAssign(&getRouteJourneyIds1Url_, getRouteJourneyIds1Url);
}
@synthesize getRouteJourneyIds1Url = getRouteJourneyIds1Url_;
- (NSString *)syncRate {
  return syncRate_;
}
- (void)setSyncRate:(NSString *)syncRate {
  JreOperatorRetainedAssign(&syncRate_, syncRate);
}
@synthesize syncRate = syncRate_;
- (NSString *)box {
  return box_;
}
- (void)setBox:(NSString *)box {
  JreOperatorRetainedAssign(&box_, box);
}
@synthesize box = box_;
- (NSString *)markerClickThru {
  return markerClickThru_;
}
- (void)setMarkerClickThru:(NSString *)markerClickThru {
  JreOperatorRetainedAssign(&markerClickThru_, markerClickThru);
}
@synthesize markerClickThru = markerClickThru_;
- (NSString *)messageClickThru {
  return messageClickThru_;
}
- (void)setMessageClickThru:(NSString *)messageClickThru {
  JreOperatorRetainedAssign(&messageClickThru_, messageClickThru);
}
@synthesize messageClickThru = messageClickThru_;
- (NSString *)bannerRefreshRate {
  return bannerRefreshRate_;
}
- (void)setBannerRefreshRate:(NSString *)bannerRefreshRate {
  JreOperatorRetainedAssign(&bannerRefreshRate_, bannerRefreshRate);
}
@synthesize bannerRefreshRate = bannerRefreshRate_;
- (NSString *)bannerClickThru {
  return bannerClickThru_;
}
- (void)setBannerClickThru:(NSString *)bannerClickThru {
  JreOperatorRetainedAssign(&bannerClickThru_, bannerClickThru);
}
@synthesize bannerClickThru = bannerClickThru_;
- (NSString *)bannerMaxImageSize {
  return bannerMaxImageSize_;
}
- (void)setBannerMaxImageSize:(NSString *)bannerMaxImageSize {
  JreOperatorRetainedAssign(&bannerMaxImageSize_, bannerMaxImageSize);
}
@synthesize bannerMaxImageSize = bannerMaxImageSize_;
- (NSString *)bannerImageUrl {
  return bannerImageUrl_;
}
- (void)setBannerImageUrl:(NSString *)bannerImageUrl {
  JreOperatorRetainedAssign(&bannerImageUrl_, bannerImageUrl);
}
@synthesize bannerImageUrl = bannerImageUrl_;
- (NSString *)helpUrl {
  return helpUrl_;
}
- (void)setHelpUrl:(NSString *)helpUrl {
  JreOperatorRetainedAssign(&helpUrl_, helpUrl);
}
@synthesize helpUrl = helpUrl_;
- (id<JavaUtilList>)initialMessages {
  return initialMessages_;
}
- (void)setInitialMessages:(id<JavaUtilList>)initialMessages {
  JreOperatorRetainedAssign(&initialMessages_, initialMessages);
}
@synthesize initialMessages = initialMessages_;

- (id)init {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&initialMessages_, [[[JavaUtilArrayList alloc] init] autorelease]);
  }
  return self;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&initialMessages_, nil);
  JreOperatorRetainedAssign(&helpUrl_, nil);
  JreOperatorRetainedAssign(&bannerImageUrl_, nil);
  JreOperatorRetainedAssign(&bannerMaxImageSize_, nil);
  JreOperatorRetainedAssign(&bannerClickThru_, nil);
  JreOperatorRetainedAssign(&bannerRefreshRate_, nil);
  JreOperatorRetainedAssign(&messageClickThru_, nil);
  JreOperatorRetainedAssign(&markerClickThru_, nil);
  JreOperatorRetainedAssign(&box_, nil);
  JreOperatorRetainedAssign(&syncRate_, nil);
  JreOperatorRetainedAssign(&getRouteJourneyIds1Url_, nil);
  JreOperatorRetainedAssign(&offRouteTimeThreshold_, nil);
  JreOperatorRetainedAssign(&offRouteCountThreshold_, nil);
  JreOperatorRetainedAssign(&offRouteDistanceThreshold_, nil);
  JreOperatorRetainedAssign(&activeEndWaitThreshold_, nil);
  JreOperatorRetainedAssign(&activeStartDisplayThreshold_, nil);
  JreOperatorRetainedAssign(&updateRate_, nil);
  JreOperatorRetainedAssign(&updateUrl_, nil);
  JreOperatorRetainedAssign(&postFeedbackUrl_, nil);
  JreOperatorRetainedAssign(&getMarkersUrl_, nil);
  JreOperatorRetainedAssign(&getMessagesUrl_, nil);
  JreOperatorRetainedAssign(&getMessageUrl_, nil);
  JreOperatorRetainedAssign(&postJourneyLocationUrl_, nil);
  JreOperatorRetainedAssign(&getMultipleJourneyLocationsUrl_, nil);
  JreOperatorRetainedAssign(&getJourneyLocationUrl_, nil);
  JreOperatorRetainedAssign(&getRouteDefinitionUrl_, nil);
  JreOperatorRetainedAssign(&getRouteJourneyIdsUrl_, nil);
  JreOperatorRetainedAssign(&datefmt_, nil);
  JreOperatorRetainedAssign(&timeoffset_, nil);
  JreOperatorRetainedAssign(&time_, nil);
  JreOperatorRetainedAssign(&timezone_, nil);
  JreOperatorRetainedAssign(&lat_, nil);
  JreOperatorRetainedAssign(&lon_, nil);
  JreOperatorRetainedAssign(&curloc_time_rate_, nil);
  JreOperatorRetainedAssign(&postloc_dist_rate_, nil);
  JreOperatorRetainedAssign(&postloc_time_rate_, nil);
  JreOperatorRetainedAssign(&oauthLogoutUrl_, nil);
  JreOperatorRetainedAssign(&oauthLoginUrl_, nil);
  JreOperatorRetainedAssign(&logoutUrl_, nil);
  JreOperatorRetainedAssign(&registerUrl_, nil);
  JreOperatorRetainedAssign(&loginUrl_, nil);
  JreOperatorRetainedAssign(&authUrl_, nil);
  JreOperatorRetainedAssign(&slug_, nil);
  JreOperatorRetainedAssign(&name_, nil);
  JreOperatorRetainedAssign(&mode_, nil);
  JreOperatorRetainedAssign(&version__, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmeApiBuspass *typedCopy = (ComAdironBusmeApiBuspass *) copy;
  typedCopy.version_ = version__;
  typedCopy.mode = mode_;
  typedCopy.name = name_;
  typedCopy.slug = slug_;
  typedCopy.authUrl = authUrl_;
  typedCopy.loginUrl = loginUrl_;
  typedCopy.registerUrl = registerUrl_;
  typedCopy.logoutUrl = logoutUrl_;
  typedCopy.oauthLoginUrl = oauthLoginUrl_;
  typedCopy.oauthLogoutUrl = oauthLogoutUrl_;
  typedCopy.postloc_time_rate = postloc_time_rate_;
  typedCopy.postloc_dist_rate = postloc_dist_rate_;
  typedCopy.curloc_time_rate = curloc_time_rate_;
  typedCopy.lon = lon_;
  typedCopy.lat = lat_;
  typedCopy.timezone = timezone_;
  typedCopy.time = time_;
  typedCopy.timeoffset = timeoffset_;
  typedCopy.datefmt = datefmt_;
  typedCopy.getRouteJourneyIdsUrl = getRouteJourneyIdsUrl_;
  typedCopy.getRouteDefinitionUrl = getRouteDefinitionUrl_;
  typedCopy.getJourneyLocationUrl = getJourneyLocationUrl_;
  typedCopy.getMultipleJourneyLocationsUrl = getMultipleJourneyLocationsUrl_;
  typedCopy.postJourneyLocationUrl = postJourneyLocationUrl_;
  typedCopy.getMessageUrl = getMessageUrl_;
  typedCopy.getMessagesUrl = getMessagesUrl_;
  typedCopy.getMarkersUrl = getMarkersUrl_;
  typedCopy.postFeedbackUrl = postFeedbackUrl_;
  typedCopy.updateUrl = updateUrl_;
  typedCopy.updateRate = updateRate_;
  typedCopy.activeStartDisplayThreshold = activeStartDisplayThreshold_;
  typedCopy.activeEndWaitThreshold = activeEndWaitThreshold_;
  typedCopy.offRouteDistanceThreshold = offRouteDistanceThreshold_;
  typedCopy.offRouteCountThreshold = offRouteCountThreshold_;
  typedCopy.offRouteTimeThreshold = offRouteTimeThreshold_;
  typedCopy.getRouteJourneyIds1Url = getRouteJourneyIds1Url_;
  typedCopy.syncRate = syncRate_;
  typedCopy.box = box_;
  typedCopy.markerClickThru = markerClickThru_;
  typedCopy.messageClickThru = messageClickThru_;
  typedCopy.bannerRefreshRate = bannerRefreshRate_;
  typedCopy.bannerClickThru = bannerClickThru_;
  typedCopy.bannerMaxImageSize = bannerMaxImageSize_;
  typedCopy.bannerImageUrl = bannerImageUrl_;
  typedCopy.helpUrl = helpUrl_;
  typedCopy.initialMessages = initialMessages_;
}

@end
