//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/api/DiscoverAPI.java
//
//  Created by polar on 5/25/13.
//

#import "JreEmulation.h"
#import "com/adiron/busme/api/APIBase.h"

@interface ComAdironBusmeApiDiscoverAPI : ComAdironBusmeApiAPIBase {
}

+ (NSString *)LOGTAG;
- (id)init;
- (BOOL)get;
@end
