//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/api/DiscoverAPIVersion1.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmeApiMaster;
@class JavaLangDouble;
@protocol JavaUtilList;

#import "JreEmulation.h"
#import "com/adiron/busme/api/DiscoverAPI.h"

@interface ComAdironBusmeApiDiscoverAPIVersion1 : ComAdironBusmeApiDiscoverAPI {
 @public
  NSString *initialUrl_;
  NSString *discoverUrl_;
  NSString *masterUrl_;
}

@property (nonatomic, copy) NSString *initialUrl;
- (NSString *)initialUrl OBJC_METHOD_FAMILY_NONE;
@property (nonatomic, copy) NSString *discoverUrl;
@property (nonatomic, copy) NSString *masterUrl;

+ (NSString *)LOGTAG;
- (NSString *)getInitialUrl;
- (NSString *)getDiscoverUrl;
- (NSString *)getMasterUrl;
- (id)initWithNSString:(NSString *)initialUrl;
+ (ComAdironBusmeApiDiscoverAPIVersion1 *)getInstanceWithNSString:(NSString *)url;
- (BOOL)get;
- (id<JavaUtilList>)discoverWithJavaLangDouble:(JavaLangDouble *)lon
                            withJavaLangDouble:(JavaLangDouble *)lat
                                       withInt:(int)zoomLevel
                                       withInt:(int)width
                                       withInt:(int)height;
- (id<JavaUtilList>)discoverWithJavaLangDouble:(JavaLangDouble *)lon
                            withJavaLangDouble:(JavaLangDouble *)lat
                                       withInt:(int)zoomLevel
                                       withInt:(int)minDim;
- (id<JavaUtilList>)discoverWithJavaLangDouble:(JavaLangDouble *)lon
                            withJavaLangDouble:(JavaLangDouble *)lat;
- (id<JavaUtilList>)discoverWithJavaLangDouble:(JavaLangDouble *)lon
                            withJavaLangDouble:(JavaLangDouble *)lat
                            withJavaLangDouble:(JavaLangDouble *)buffer;
- (ComAdironBusmeApiMaster *)findMasterWithNSString:(NSString *)slug;
@end
