//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/api/DiscoverAPI.java
//
//  Created by polar on 5/25/13.
//

#import "IOSClass.h"
#import "com/adiron/busme/api/DiscoverAPI.h"

@implementation ComAdironBusmeApiDiscoverAPI

static NSString * ComAdironBusmeApiDiscoverAPI_LOGTAG_;

+ (NSString *)LOGTAG {
  return ComAdironBusmeApiDiscoverAPI_LOGTAG_;
}

- (id)init {
  return [super init];
}

- (BOOL)get {
  return NO;
}

+ (void)initialize {
  if (self == [ComAdironBusmeApiDiscoverAPI class]) {
    JreOperatorRetainedAssign(&ComAdironBusmeApiDiscoverAPI_LOGTAG_, [[IOSClass classWithClass:[ComAdironBusmeApiDiscoverAPI class]] getName]);
  }
}

- (void)dealloc {
  [super dealloc];
}

@end
