//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/api/JourneyLocation.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/api/JourneyLocation.h"

@implementation ComAdironBusmeApiJourneyLocation

- (NSString *)id_ {
  return id__;
}
- (void)setId_:(NSString *)id_ {
  JreOperatorRetainedAssign(&id__, id_);
}
@synthesize id_ = id__;
@synthesize lat = lat_;
@synthesize lon = lon_;
@synthesize dir = dir_;
@synthesize reported_time = reported_time_;
@synthesize recorded_time = recorded_time_;
@synthesize timediff = timediff_;
@synthesize onroute = onroute_;
@synthesize reported = reported_;
@synthesize distance = distance_;

- (id)init {
  return [super init];
}

- (void)dealloc {
  JreOperatorRetainedAssign(&id__, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmeApiJourneyLocation *typedCopy = (ComAdironBusmeApiJourneyLocation *) copy;
  typedCopy.id_ = id__;
  typedCopy.lat = lat_;
  typedCopy.lon = lon_;
  typedCopy.dir = dir_;
  typedCopy.reported_time = reported_time_;
  typedCopy.recorded_time = recorded_time_;
  typedCopy.timediff = timediff_;
  typedCopy.onroute = onroute_;
  typedCopy.reported = reported_;
  typedCopy.distance = distance_;
}

@end
