//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/api/Master.java
//
//  Created by polar on 5/25/13.
//

@class JavaLangFloat;

#import "JreEmulation.h"

@interface ComAdironBusmeApiMaster : NSObject {
 @public
  JavaLangFloat *lon_, *lat_;
  NSString *slug_;
  NSString *name_;
  NSString *apiUrl_;
}

@property (nonatomic, retain) JavaLangFloat *lon;
@property (nonatomic, retain) JavaLangFloat *lat;
@property (nonatomic, copy) NSString *slug;
@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSString *apiUrl;

- (id)init;
@end
