//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/api/Master.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/api/Master.h"
#import "java/lang/Float.h"

@implementation ComAdironBusmeApiMaster

- (JavaLangFloat *)lon {
  return lon_;
}
- (void)setLon:(JavaLangFloat *)lon {
  JreOperatorRetainedAssign(&lon_, lon);
}
@synthesize lon = lon_;
- (JavaLangFloat *)lat {
  return lat_;
}
- (void)setLat:(JavaLangFloat *)lat {
  JreOperatorRetainedAssign(&lat_, lat);
}
@synthesize lat = lat_;
- (NSString *)slug {
  return slug_;
}
- (void)setSlug:(NSString *)slug {
  JreOperatorRetainedAssign(&slug_, slug);
}
@synthesize slug = slug_;
- (NSString *)name {
  return name_;
}
- (void)setName:(NSString *)name {
  JreOperatorRetainedAssign(&name_, name);
}
@synthesize name = name_;
- (NSString *)apiUrl {
  return apiUrl_;
}
- (void)setApiUrl:(NSString *)apiUrl {
  JreOperatorRetainedAssign(&apiUrl_, apiUrl);
}
@synthesize apiUrl = apiUrl_;

- (id)init {
  return [super init];
}

- (void)dealloc {
  JreOperatorRetainedAssign(&apiUrl_, nil);
  JreOperatorRetainedAssign(&name_, nil);
  JreOperatorRetainedAssign(&slug_, nil);
  JreOperatorRetainedAssign(&lat_, nil);
  JreOperatorRetainedAssign(&lon_, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmeApiMaster *typedCopy = (ComAdironBusmeApiMaster *) copy;
  typedCopy.lon = lon_;
  typedCopy.lat = lat_;
  typedCopy.slug = slug_;
  typedCopy.name = name_;
  typedCopy.apiUrl = apiUrl_;
}

@end
