//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/api/NameId.java
//
//  Created by polar on 5/25/13.
//

#import "IOSObjectArray.h"
#import "com/adiron/busme/api/NameId.h"
#import "java/lang/Long.h"

@implementation ComAdironBusmeApiNameId

- (NSString *)name {
  return name_;
}
- (void)setName:(NSString *)name {
  JreOperatorRetainedAssign(&name_, name);
}
@synthesize name = name_;
- (NSString *)id_ {
  return id__;
}
- (void)setId_:(NSString *)id_ {
  JreOperatorRetainedAssign(&id__, id_);
}
@synthesize id_ = id__;
- (NSString *)route_id {
  return route_id_;
}
- (void)setRoute_id:(NSString *)route_id {
  JreOperatorRetainedAssign(&route_id_, route_id);
}
@synthesize route_id = route_id_;
- (NSString *)type {
  return type_;
}
- (void)setType:(NSString *)type {
  JreOperatorRetainedAssign(&type_, type);
}
@synthesize type = type_;
@synthesize version_ = version__;

- (id)initWithNSString:(NSString *)name
          withNSString:(NSString *)id_ {
  if ((self = [super init])) {
    version__ = -1;
    self.name = [NIL_CHK(name) trim];
    self.id_ = [NIL_CHK(id_) trim];
  }
  return self;
}

- (id)initWithNSStringArray:(IOSObjectArray *)name_id {
  if ((self = [super init])) {
    version__ = -1;
    self.name = [((NSString *) [((IOSObjectArray *) NIL_CHK(name_id)) objectAtIndex:0]) trim];
    self.id_ = [((NSString *) [((IOSObjectArray *) NIL_CHK(name_id)) objectAtIndex:1]) trim];
    if ((int) [((IOSObjectArray *) NIL_CHK(name_id)) count] > 2) self.type = [((NSString *) [((IOSObjectArray *) NIL_CHK(name_id)) objectAtIndex:2]) trim];
    if ([@"R" isEqual:self.type] && (int) [((IOSObjectArray *) NIL_CHK(name_id)) count] == 4) {
      self.version_ = [JavaLangLong parseLongWithNSString:((NSString *) [((IOSObjectArray *) NIL_CHK(name_id)) objectAtIndex:3])];
    }
    else if ([@"V" isEqual:self.type] && (int) [((IOSObjectArray *) NIL_CHK(name_id)) count] == 5) {
      self.route_id = ((NSString *) [((IOSObjectArray *) NIL_CHK(name_id)) objectAtIndex:3]);
      self.version_ = [JavaLangLong parseLongWithNSString:((NSString *) [((IOSObjectArray *) NIL_CHK(name_id)) objectAtIndex:4])];
    }
  }
  return self;
}

- (NSString *)description {
  return name_;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&type_, nil);
  JreOperatorRetainedAssign(&route_id_, nil);
  JreOperatorRetainedAssign(&id__, nil);
  JreOperatorRetainedAssign(&name_, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmeApiNameId *typedCopy = (ComAdironBusmeApiNameId *) copy;
  typedCopy.name = name_;
  typedCopy.id_ = id__;
  typedCopy.route_id = route_id_;
  typedCopy.type = type_;
  typedCopy.version_ = version__;
}

@end
