//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/api/Storage.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/api/Storage.h"

@implementation ComAdironBusmeApiStorage

- (void)preSerializeWithId:(id)api {
}

- (void)postSerializeWithId:(id)api {
}

- (id)init {
  return [super init];
}

- (void)dealloc {
  [super dealloc];
}

@end
