//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/api/Storage.java
//
//  Created by polar on 5/25/13.
//

#import "JreEmulation.h"
#import "java/io/Serializable.h"

@interface ComAdironBusmeApiStorage : NSObject < JavaIoSerializable > {
}

- (void)preSerializeWithId:(id)api;
- (void)postSerializeWithId:(id)api;
- (id)init;
@end
