//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/org/osmdroid/api/IGeoPoint.java
//
//  Created by polar on 5/25/13.
//

void OrgOsmdroidApiIGeoPoint_unused() {}
