//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/ActivityAPI.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmeApiAPIBase_Tag;
@class ComAdironBusmeApiBannerInfo;
@class ComAdironBusmeApiBuspass;
@class ComAdironBusmeApiBuspassAPI_Login;
@class ComAdironBusmeApiJourneyLocation;
@class ComAdironBusmeApiJourneyPattern;
@class ComAdironBusmeApiMaster;
@class ComAdironBusmeApiMasterMessage;
@class ComAdironBusmeApiNameId;
@class ComAdironBusmeApiRoute;
@class ComAdironBusmePlatformActivityAPI_$2;
@class ComAdironBusmePlatformActivityAPI_BuspassEventNotifier;
@class ComAdironBusmePlatformActivityAPI_LocRoute;
@class ComAdironBusmePlatformArguments;
@class ComAdironBusmePlatformBannerStore;
@class ComAdironBusmePlatformBusmeActivityController;
@class ComAdironBusmePlatformBusmeConfigurator;
@class ComAdironBusmePlatformBuspassEvent;
@class ComAdironBusmePlatformHandler;
@class ComAdironBusmePlatformJourneyLocationPoster;
@class ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_ReasonEnum;
@class ComAdironBusmePlatformJourneyStore;
@class ComAdironBusmePlatformLocation;
@class ComAdironBusmePlatformLoginManager;
@class ComAdironBusmePlatformLoginManager_LoginContinuation;
@class ComAdironBusmePlatformMessageStore;
@class IOSObjectArray;
@protocol ComAdironBusmePlatformBuspassEventListener;
@protocol ComAdironBusmePlatformLocationListener;
@protocol ComAdironBusmePlatformProgressLogger;
@protocol JavaUtilCollection;
@protocol JavaUtilList;
@protocol JavaUtilMap;
@protocol OrgOsmdroidApiIGeoPoint;

#import "JreEmulation.h"
#import "com/adiron/busme/api/BuspassAPI.h"
#import "com/adiron/busme/platform/JourneyLocationPoster.h"
#import "com/adiron/busme/platform/OnLocatorSelectedListener.h"
#import "java/lang/Runnable.h"
#import "java/util/Comparator.h"
#import "java/util/Observable.h"
#import "java/util/Observer.h"

@interface ComAdironBusmePlatformActivityAPI : ComAdironBusmeApiBuspassAPI < ComAdironBusmePlatformOnLocatorSelectedListener > {
 @public
  ComAdironBusmePlatformBusmeConfigurator *configurator_;
  NSString *masterName_;
  NSString *masterSlug_;
  id<JavaUtilMap> eventListeners_;
  ComAdironBusmePlatformJourneyLocationPoster *journeyLocationPoster_;
}

@property (nonatomic, retain) ComAdironBusmePlatformBusmeConfigurator *configurator;
@property (nonatomic, copy) NSString *masterName;
@property (nonatomic, copy) NSString *masterSlug;
@property (nonatomic, retain) id<JavaUtilMap> eventListeners;
@property (nonatomic, retain) ComAdironBusmePlatformJourneyLocationPoster *journeyLocationPoster;

+ (NSString *)LOGTAG;
- (id)initWithNSString:(NSString *)initialUrl
          withNSString:(NSString *)platform
          withNSString:(NSString *)appVersion;
- (ComAdironBusmePlatformBusmeConfigurator *)getConfigurator;
- (void)setConfiguratorWithComAdironBusmePlatformBusmeConfigurator:(ComAdironBusmePlatformBusmeConfigurator *)configurator;
- (void)setMasterWithComAdironBusmeApiMaster:(ComAdironBusmeApiMaster *)master;
- (NSString *)getMasterName;
- (void)setMasterNameWithNSString:(NSString *)masterName;
- (NSString *)getMasterSlug;
- (void)setMasterSlugWithNSString:(NSString *)masterSlug;
- (ComAdironBusmeApiBuspass *)get;
- (BOOL)isLoggedIn;
- (ComAdironBusmeApiBuspassAPI_Login *)getLogin;
- (void)onLocatorSelectedWithJavaUtilList:(id<JavaUtilList>)routes;
- (NSString *)getTrackingArgs;
- (id<JavaUtilList>)getNameIdsWithNSString:(NSString *)url;
- (id<JavaUtilList>)getRouteJourneyIds;
- (NSString *)joinWithNSStringArray:(IOSObjectArray *)ss
                       withNSString:(NSString *)delimeter;
- (void)postJourneyLocationWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)r
                   withComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)location
                                         withNSString:(NSString *)role;
- (void)postFeedbackWithNSString:(NSString *)message;
- (ComAdironBusmeApiRoute *)getRouteDefinitionWithComAdironBusmeApiNameId:(ComAdironBusmeApiNameId *)name;
- (ComAdironBusmeApiJourneyPattern *)getJourneyPatternWithNSString:(NSString *)id_;
- (id<JavaUtilMap>)getMarkersXMLWithJavaUtilCollection:(id<JavaUtilCollection>)collection;
- (id<JavaUtilMap>)getMessagesXMLWithJavaUtilCollection:(id<JavaUtilCollection>)collection;
- (id<JavaUtilMap>)getMultipleJourneyLocationsXMLWithJavaUtilList:(id<JavaUtilList>)journeys;
- (ComAdironBusmeApiJourneyLocation *)getJourneyLocationXMLWithComAdironBusmeApiNameId:(ComAdironBusmeApiNameId *)nameid;
- (NSString *)getMarkerClickThruWithNSString:(NSString *)id_;
- (NSString *)getMessageClickThruWithNSString:(NSString *)id_;
- (NSString *)getBannerClickThruWithNSString:(NSString *)id_;
- (id<JavaUtilList>)getAllCloseJourneysWithComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)location
                                                                  withInt:(int)feet;
- (id<JavaUtilList>)getActiveJourneys;
- (void)triggerEventWithNSString:(NSString *)eventName
                          withId:(id)data;
- (void)triggerEventWithNSString:(NSString *)eventName;
- (void)registerForEventWithNSString:(NSString *)eventName
withComAdironBusmePlatformBuspassEventListener:(id<ComAdironBusmePlatformBuspassEventListener>)event;
- (ComAdironBusmeApiAPIBase_Tag *)postAndParseTagWithNSString:(NSString *)url
                                             withJavaUtilList:(id<JavaUtilList>)params;
- (NSString *)getPreselectJourneyMessageWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)route;
- (void)onLocatorMenuSelectWithNSString:(NSString *)roleIntent;
- (void)stopPosting;
- (NSString *)getPostingRole;
- (void)onSelectJourneyForPostingWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)route
                                               withNSString:(NSString *)role;
- (void)zoomToMasterSpan;
- (void)forceNewGetWithJavaLangRunnable:(id<JavaLangRunnable>)success
                   withJavaLangRunnable:(id<JavaLangRunnable>)networkFailure
                   withJavaLangRunnable:(id<JavaLangRunnable>)exception;
- (NSString *)getDiscoverUrl;
- (ComAdironBusmePlatformJourneyStore *)getJourneyStore;
- (ComAdironBusmePlatformBannerStore *)getBannerStore;
- (ComAdironBusmePlatformMessageStore *)getMessageStore;
- (NSString *)formatWithInt:(int)format
          withNSObjectArray:(IOSObjectArray *)args;
- (BOOL)hasAdequateLocationForPostingLocations;
- (ComAdironBusmePlatformLocation *)getLastFix;
- (ComAdironBusmePlatformBusmeActivityController *)getBusmeActivityController;
- (ComAdironBusmePlatformLoginManager *)getLoginManager;
- (NSString *)retreiveStoredAuthToken;
- (void)forgetUser;
- (ComAdironBusmePlatformHandler *)getUIHandler;
- (ComAdironBusmePlatformHandler *)getBackgroundHandler;
- (void)requestLocationUpdatesWithInt:(int)time
                              withInt:(int)dist
withComAdironBusmePlatformLocationListener:(id<ComAdironBusmePlatformLocationListener>)listener;
- (void)removeUpdatesWithComAdironBusmePlatformLocationListener:(id<ComAdironBusmePlatformLocationListener>)listener;
- (id<ComAdironBusmePlatformProgressLogger>)getProgressLoggerWithBOOL:(BOOL)showwelcome;
- (void)disableLocationBasedRouteFinder;
- (void)enableLocationBasedRouteFinder;
- (void)enableLocationBasedRouteFinderWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)route
                                                    withNSString:(NSString *)role;
- (void)storeCredentialsWithComAdironBusmeApiBuspassAPI_Login:(ComAdironBusmeApiBuspassAPI_Login *)login;
- (void)removeCredentialsAuthTokenWithComAdironBusmeApiBuspassAPI_Login:(ComAdironBusmeApiBuspassAPI_Login *)login;
- (void)invalidateMap;
- (BOOL)UIisMessagePopupShowing;
- (void)UIShowMessagePopupWithComAdironBusmeApiMasterMessage:(ComAdironBusmeApiMasterMessage *)message;
- (void)UILaunchLoginDialogWithComAdironBusmePlatformArguments:(ComAdironBusmePlatformArguments *)args
      withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)success
      withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)failure;
- (void)UILaunchRegistrationDialogWithComAdironBusmePlatformArguments:(ComAdironBusmePlatformArguments *)args
             withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)success
             withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)failure;
- (void)UIShowProgressDialogWithInt:(int)title
                            withInt:(int)message;
- (void)UIShowProgressDialogWithNSString:(NSString *)title
                            withNSString:(NSString *)message;
- (void)UIShowWhichBusDialogWithNSString:(NSString *)roleIntent
                        withJavaUtilList:(id<JavaUtilList>)routes;
- (void)UISetProgressBarIndeterminateVisibilityWithBOOL:(BOOL)visible;
- (BOOL)UIShouldShowWelcome;
- (void)UIShowWelcomeDialogWithNSString:(NSString *)name;
- (void)UIDismissWelcomeDialog;
- (void)UIDismissProgressDialog;
- (void)UIShowAlertDialogWithInt:(int)title
                         withInt:(int)message;
- (void)UIShowAlertDialogWithNSString:(NSString *)title
                         withNSString:(NSString *)message;
- (void)UIShowShortToastWithNSString:(NSString *)message;
- (void)UIShowLongToastWithNSString:(NSString *)message;
- (void)UIShowLongToastWithInt:(int)message;
- (void)UIShowBannerWithComAdironBusmeApiBannerInfo:(ComAdironBusmeApiBannerInfo *)banner;
- (void)UIHideBanner;
@end

@interface ComAdironBusmePlatformActivityAPI_BuspassEventNotifier : JavaUtilObservable {
}

- (void)setChanged;
- (id)initWithComAdironBusmePlatformActivityAPI:(ComAdironBusmePlatformActivityAPI *)outer$;
@end

@interface ComAdironBusmePlatformActivityAPI_BuspassEventListenerProxy : NSObject < JavaUtilObserver > {
 @public
  id<ComAdironBusmePlatformBuspassEventListener> eventListener_;
}

@property (nonatomic, retain) id<ComAdironBusmePlatformBuspassEventListener> eventListener;

- (id)initWithComAdironBusmePlatformActivityAPI:(ComAdironBusmePlatformActivityAPI *)outer$
 withComAdironBusmePlatformBuspassEventListener:(id<ComAdironBusmePlatformBuspassEventListener>)lis;
- (void)updateWithJavaUtilObservable:(JavaUtilObservable *)arg0
                              withId:(id)obj;
@end

@interface ComAdironBusmePlatformActivityAPI_LocRoute : NSObject {
 @public
  id<OrgOsmdroidApiIGeoPoint> loc_;
  ComAdironBusmeApiRoute *route_;
}

@property (nonatomic, retain) id<OrgOsmdroidApiIGeoPoint> loc;
@property (nonatomic, retain) ComAdironBusmeApiRoute *route;

- (id)initWithComAdironBusmePlatformActivityAPI:(ComAdironBusmePlatformActivityAPI *)outer$
                    withOrgOsmdroidApiIGeoPoint:(id<OrgOsmdroidApiIGeoPoint>)a1
                     withComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)a2;
@end

@interface ComAdironBusmePlatformActivityAPI_LocRouteComparator : NSObject < JavaUtilComparator > {
 @public
  id<OrgOsmdroidApiIGeoPoint> origin_;
}

@property (nonatomic, retain) id<OrgOsmdroidApiIGeoPoint> origin;

- (id)initWithComAdironBusmePlatformActivityAPI:(ComAdironBusmePlatformActivityAPI *)outer$
                    withOrgOsmdroidApiIGeoPoint:(id<OrgOsmdroidApiIGeoPoint>)origin;
- (int)compareWithId:(ComAdironBusmePlatformActivityAPI_LocRoute *)arg0
              withId:(ComAdironBusmePlatformActivityAPI_LocRoute *)arg1;
@end

@interface ComAdironBusmePlatformActivityAPI_$1 : NSObject < JavaLangRunnable > {
 @public
  NSString *val$eventName_;
  ComAdironBusmePlatformActivityAPI_BuspassEventNotifier *val$obs_;
  ComAdironBusmePlatformBuspassEvent *val$event_;
}

@property (nonatomic, copy) NSString *val$eventName;
@property (nonatomic, retain) ComAdironBusmePlatformActivityAPI_BuspassEventNotifier *val$obs;
@property (nonatomic, retain) ComAdironBusmePlatformBuspassEvent *val$event;

- (void)run;
- (id)initWithNSString:(NSString *)capture$0
withComAdironBusmePlatformActivityAPI_BuspassEventNotifier:(ComAdironBusmePlatformActivityAPI_BuspassEventNotifier *)capture$1
withComAdironBusmePlatformBuspassEvent:(ComAdironBusmePlatformBuspassEvent *)capture$2;
@end

@interface ComAdironBusmePlatformActivityAPI_$2 : NSObject < ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener > {
 @public
  ComAdironBusmePlatformActivityAPI *this$0_;
  NSString *val$role_;
}

@property (nonatomic, retain) ComAdironBusmePlatformActivityAPI *this$0;
@property (nonatomic, copy) NSString *val$role;

- (void)onOffRouteEventWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)r
               withComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)loc;
- (void)atRouteEndWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)r;
- (void)atRouteStartWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)r;
- (void)onOnRouteEventWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)r
              withComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)loc;
- (void)onRoutePostingWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)r;
- (void)onRouteDoneWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)r
withComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_ReasonEnum:(ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_ReasonEnum *)reason;
- (id)initWithComAdironBusmePlatformActivityAPI:(ComAdironBusmePlatformActivityAPI *)outer$
                                   withNSString:(NSString *)capture$0;
@end

@interface ComAdironBusmePlatformActivityAPI_$2_$1 : NSObject < JavaLangRunnable > {
 @public
  ComAdironBusmePlatformActivityAPI_$2 *this$0_;
  ComAdironBusmeApiRoute *val$r_;
  ComAdironBusmePlatformLocation *val$loc_;
}

@property (nonatomic, retain) ComAdironBusmePlatformActivityAPI_$2 *this$0;
@property (nonatomic, retain) ComAdironBusmeApiRoute *val$r;
@property (nonatomic, retain) ComAdironBusmePlatformLocation *val$loc;

- (void)run;
- (id)initWithComAdironBusmePlatformActivityAPI_$2:(ComAdironBusmePlatformActivityAPI_$2 *)outer$
                        withComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)capture$0
                withComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)capture$1;
@end

@interface ComAdironBusmePlatformActivityAPI_$3 : NSObject < JavaLangRunnable > {
 @public
  ComAdironBusmePlatformActivityAPI *this$0_;
  id<JavaLangRunnable> val$success_;
}

@property (nonatomic, retain) ComAdironBusmePlatformActivityAPI *this$0;
@property (nonatomic, retain) id<JavaLangRunnable> val$success;

- (void)run;
- (id)initWithComAdironBusmePlatformActivityAPI:(ComAdironBusmePlatformActivityAPI *)outer$
                           withJavaLangRunnable:(id<JavaLangRunnable>)capture$0;
@end

@interface ComAdironBusmePlatformActivityAPI_$4 : NSObject < JavaLangRunnable > {
 @public
  ComAdironBusmePlatformActivityAPI *this$0_;
  id<JavaLangRunnable> val$success_;
}

@property (nonatomic, retain) ComAdironBusmePlatformActivityAPI *this$0;
@property (nonatomic, retain) id<JavaLangRunnable> val$success;

- (void)run;
- (id)initWithComAdironBusmePlatformActivityAPI:(ComAdironBusmePlatformActivityAPI *)outer$
                           withJavaLangRunnable:(id<JavaLangRunnable>)capture$0;
@end
