//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/BannersRequestProcessor.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmeApiAPIBase_Tag;
@class ComAdironBusmePlatformBannerBasket;
@protocol ComAdironBusmePlatformBannersRequestProcessor_OnBannersResponseListener;
@protocol JavaUtilList;
@protocol JavaUtilMap;

#import "JreEmulation.h"
#import "com/adiron/busme/platform/RequestUpdater.h"

@interface ComAdironBusmePlatformBannersRequestProcessor : NSObject < ComAdironBusmePlatformRequestUpdater_ArgumentsPreparer, ComAdironBusmePlatformRequestUpdater_ResponseProcessor > {
 @public
  ComAdironBusmePlatformBannerBasket *bannerBasket_;
  id<ComAdironBusmePlatformBannersRequestProcessor_OnBannersResponseListener> responseListener_;
}

@property (nonatomic, retain) ComAdironBusmePlatformBannerBasket *bannerBasket;
@property (nonatomic, retain) id<ComAdironBusmePlatformBannersRequestProcessor_OnBannersResponseListener> responseListener;

+ (NSString *)LOGTAG;
- (id)init;
- (id)initWithComAdironBusmePlatformBannerBasket:(ComAdironBusmePlatformBannerBasket *)bannerBasket
withComAdironBusmePlatformBannersRequestProcessor_OnBannersResponseListener:(id<ComAdironBusmePlatformBannersRequestProcessor_OnBannersResponseListener>)responseListener;
- (ComAdironBusmePlatformBannerBasket *)getBannerBasket;
- (void)setBannerBasketWithComAdironBusmePlatformBannerBasket:(ComAdironBusmePlatformBannerBasket *)bannerBasket;
- (id<ComAdironBusmePlatformBannersRequestProcessor_OnBannersResponseListener>)getResponseListener;
- (void)setResponseListenerWithComAdironBusmePlatformBannersRequestProcessor_OnBannersResponseListener:(id<ComAdironBusmePlatformBannersRequestProcessor_OnBannersResponseListener>)responseListener;
- (void)processResponseWithComAdironBusmeApiAPIBase_Tag:(ComAdironBusmeApiAPIBase_Tag *)response;
- (id<JavaUtilList>)getArguments;
@end

@protocol ComAdironBusmePlatformBannersRequestProcessor_OnBannersResponseListener < NSObject >
- (void)onResponseWithJavaUtilMap:(id<JavaUtilMap>)response;
@end
