//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/BannerBasket.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmeApiBannerInfo;
@class ComAdironBusmePlatformActivityAPI;
@class ComAdironBusmePlatformBannerBasket_Starter;
@class ComAdironBusmePlatformBannerStore;
@class ComAdironBusmePlatformBannersController;
@class ComAdironBusmePlatformLocation;
@protocol JavaUtilCollection;

#import "JreEmulation.h"
#import "com/adiron/busme/platform/LocationListener.h"
#import "java/lang/Runnable.h"

@interface ComAdironBusmePlatformBannerBasket : NSObject < ComAdironBusmePlatformLocationListener > {
 @public
  ComAdironBusmePlatformActivityAPI *activityAPI_;
  ComAdironBusmePlatformBannerStore *bannerStore_;
  ComAdironBusmePlatformBannersController *bannerController_;
  ComAdironBusmePlatformBannerBasket_Starter *starter_;
  BOOL stopped_;
}

@property (nonatomic, retain) ComAdironBusmePlatformActivityAPI *activityAPI;
@property (nonatomic, retain) ComAdironBusmePlatformBannerStore *bannerStore;
@property (nonatomic, retain) ComAdironBusmePlatformBannersController *bannerController;
@property (nonatomic, retain) ComAdironBusmePlatformBannerBasket_Starter *starter;
@property (nonatomic, assign) BOOL stopped;

+ (NSString *)LOGTAG;
- (ComAdironBusmePlatformBannerStore *)getBannerStore;
- (void)setBannerStoreWithComAdironBusmePlatformBannerStore:(ComAdironBusmePlatformBannerStore *)bannerStore;
- (ComAdironBusmePlatformActivityAPI *)getActivityAPI;
- (id)initWithComAdironBusmePlatformActivityAPI:(ComAdironBusmePlatformActivityAPI *)api
          withComAdironBusmePlatformBannerStore:(ComAdironBusmePlatformBannerStore *)store
    withComAdironBusmePlatformBannersController:(ComAdironBusmePlatformBannersController *)controller;
- (id<JavaUtilCollection>)getBanners;
- (BOOL)addBannerWithComAdironBusmeApiBannerInfo:(ComAdironBusmeApiBannerInfo *)info;
- (void)removeBannerWithNSString:(NSString *)key;
- (void)start;
- (void)stop;
- (void)onLocationChangedWithComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)location;
- (void)onProviderDisabledWithNSString:(NSString *)provider;
- (void)onProviderEnabledWithNSString:(NSString *)provider;
- (void)onStatusChangedWithNSString:(NSString *)provider
                            withInt:(int)status;
@end

@interface ComAdironBusmePlatformBannerBasket_Starter : NSObject < JavaLangRunnable > {
 @public
  ComAdironBusmePlatformBannerBasket *this$0_;
}

@property (nonatomic, retain) ComAdironBusmePlatformBannerBasket *this$0;

- (void)run;
- (id)initWithComAdironBusmePlatformBannerBasket:(ComAdironBusmePlatformBannerBasket *)outer$;
@end
