//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/BusmeGeographyController.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/platform/BusmeGeographyController.h"

@implementation ComAdironBusmePlatformBusmeGeographyController

- (id)init {
  return [super init];
}

- (void)dealloc {
  [super dealloc];
}

@end
