//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/BuspassEvent.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/platform/BuspassEvent.h"

@implementation ComAdironBusmePlatformBuspassEvent

static NSString * ComAdironBusmePlatformBuspassEvent_LocationsUpdated_ = @"locationsUpdated";

- (NSString *)eventName {
  return eventName_;
}
- (void)setEventName:(NSString *)eventName {
  JreOperatorRetainedAssign(&eventName_, eventName);
}
@synthesize eventName = eventName_;
- (id)eventData {
  return eventData_;
}
- (void)setEventData:(id)eventData {
  JreOperatorRetainedAssign(&eventData_, eventData);
}
@synthesize eventData = eventData_;

+ (NSString *)LocationsUpdated {
  return ComAdironBusmePlatformBuspassEvent_LocationsUpdated_;
}

- (id)initWithNSString:(NSString *)eventName
                withId:(id)eventData {
  if ((self = [super init])) {
    self.eventName = eventName;
    self.eventData = eventData;
  }
  return self;
}

- (id)getEventData {
  return eventData_;
}

- (NSString *)getEventName {
  return eventName_;
}

- (NSString *)description {
  return eventName_;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&eventData_, nil);
  JreOperatorRetainedAssign(&eventName_, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmePlatformBuspassEvent *typedCopy = (ComAdironBusmePlatformBuspassEvent *) copy;
  typedCopy.eventName = eventName_;
  typedCopy.eventData = eventData_;
}

@end
