//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/BuspassEvent.java
//
//  Created by polar on 5/25/13.
//

#import "JreEmulation.h"

@interface ComAdironBusmePlatformBuspassEvent : NSObject {
 @public
  NSString *eventName_;
  id eventData_;
}

@property (nonatomic, copy) NSString *eventName;
@property (nonatomic, retain) id eventData;

+ (NSString *)LocationsUpdated;
- (id)initWithNSString:(NSString *)eventName
                withId:(id)eventData;
- (id)getEventData;
- (NSString *)getEventName;
- (NSString *)description;
@end
