//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/Constants.java
//
//  Created by polar on 5/25/13.
//

#import "JreEmulation.h"

@interface ComAdironBusmePlatformConstants : NSObject {
}

+ (NSString *)AUTHTOKEN_TYPE;
+ (NSString *)ACCOUNT_TYPE;
- (id)init;
@end
