//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/DisplayPlaneModelController.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/api/MarkerInfo.h"
#import "com/adiron/busme/integration/BoundingBoxE6.h"
#import "com/adiron/busme/integration/DisplayPlaneModelController.h"
#import "com/adiron/busme/platform/DisplayPlaneModelController.h"
#import "com/adiron/busme/platform/JourneyDisplay.h"
#import "org/osmdroid/api/IGeoPoint.h"

@implementation ComAdironBusmePlatformDisplayPlaneModelController

- (ComAdironBusmeIntegrationDisplayPlaneModelController *)delegate {
  return delegate_;
}
- (void)setDelegate:(ComAdironBusmeIntegrationDisplayPlaneModelController *)delegate {
  JreOperatorRetainedAssign(&delegate_, delegate);
}
@synthesize delegate = delegate_;

- (id)initWithComAdironBusmeIntegrationDisplayPlaneModelController:(ComAdironBusmeIntegrationDisplayPlaneModelController *)d {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&delegate_, d);
  }
  return self;
}

- (ComAdironBusmeIntegrationDisplayPlaneModelController *)getIntegration {
  return delegate_;
}

- (void)setHighlightDurationWithLongInt:(long long int)highlightDuration {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) setHighlightDurationWithLongInt:highlightDuration];
}

- (void)setNearbyStateWithBOOL:(BOOL)b {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) setNearbyStateWithBOOL:b];
}

- (void)setOnlyActiveStateWithBOOL:(BOOL)b {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) setOnlyActiveStateWithBOOL:b];
}

- (void)setNearbyDistanceWithInt:(int)nearbyDistance {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) setNearbyDistanceWithInt:nearbyDistance];
}

- (void)setSyncRefreshRateWithInt:(int)seconds {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) setSyncRefreshRateWithInt:seconds];
}

- (void)addMarkerWithComAdironBusmeApiMarkerInfo:(ComAdironBusmeApiMarkerInfo *)marker {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) addMarkerWithComAdironBusmeApiMarkerInfo:marker];
}

- (void)removeMarkerWithComAdironBusmeApiMarkerInfo:(ComAdironBusmeApiMarkerInfo *)marker {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) removeMarkerWithComAdironBusmeApiMarkerInfo:marker];
}

- (void)removeMarkerWithNSString:(NSString *)id_ {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) removeMarkerWithNSString:id_];
}

- (void)removeAllMarkers {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) removeAllMarkers];
}

- (void)setHighlightJourneyDisplayWithComAdironBusmePlatformJourneyDisplay:(ComAdironBusmePlatformJourneyDisplay *)route {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) setHighlightJourneyDisplayWithComAdironBusmePlatformJourneyDisplay:route];
}

- (ComAdironBusmePlatformJourneyDisplay *)getHighlightJourneyDisplay {
  return [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) getHighlightJourneyDisplay];
}

- (void)unsetHighlight {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) unsetHighlight];
}

- (void)setTrackingJourneyDisplayWithComAdironBusmePlatformJourneyDisplay:(ComAdironBusmePlatformJourneyDisplay *)route {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) setTrackingJourneyDisplayWithComAdironBusmePlatformJourneyDisplay:route];
}

- (ComAdironBusmePlatformJourneyDisplay *)getTrackingJourneyDisplay {
  return [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) getTrackingJourneyDisplay];
}

- (BOOL)isTracking {
  return [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) isTracking];
}

- (void)unsetTracking {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) unsetTracking];
}

- (id<OrgOsmdroidApiIGeoPoint>)getMyLocation {
  return [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) getMyLocation];
}

- (void)animateToCurrentLocation {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) animateToCurrentLocation];
}

- (void)addJourneyDisplayWithComAdironBusmePlatformJourneyDisplay:(ComAdironBusmePlatformJourneyDisplay *)route {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) addJourneyDisplayWithComAdironBusmePlatformJourneyDisplay:route];
}

- (void)removeJourneyDisplayWithComAdironBusmePlatformJourneyDisplay:(ComAdironBusmePlatformJourneyDisplay *)route {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) removeJourneyDisplayWithComAdironBusmePlatformJourneyDisplay:route];
}

- (void)removeAllJourneyDisplays {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) removeAllJourneyDisplays];
}

- (void)notifyStateChange {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) notifyStateChange];
}

- (void)mapZoomToSpanWithComAdironBusmeIntegrationBoundingBoxE6:(ComAdironBusmeIntegrationBoundingBoxE6 *)boundingBox {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) mapZoomToSpanWithComAdironBusmeIntegrationBoundingBoxE6:boundingBox];
}

- (void)invalidate {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) invalidate];
}

- (void)clearTileCache {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) clearTileCache];
}

- (void)onCreate {
  [((ComAdironBusmeIntegrationDisplayPlaneModelController *) NIL_CHK(delegate_)) onCreate];
}

- (void)dealloc {
  JreOperatorRetainedAssign(&delegate_, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmePlatformDisplayPlaneModelController *typedCopy = (ComAdironBusmePlatformDisplayPlaneModelController *) copy;
  typedCopy.delegate = delegate_;
}

@end
