//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/GeoPointSerializable.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/integration/GeoPoint.h"
#import "com/adiron/busme/platform/GeoPointSerializable.h"
#import "org/osmdroid/api/IGeoPoint.h"

@implementation ComAdironBusmePlatformGeoPointSerializable

@synthesize latitude = latitude_;
@synthesize longitude = longitude_;

- (id)init {
  return [super init];
}

- (id)initWithInt:(int)latitudeE6
          withInt:(int)longitudeE6 {
  if ((self = [super init])) {
    latitude_ = latitudeE6;
    longitude_ = longitudeE6;
  }
  return self;
}

- (id)initWithOrgOsmdroidApiIGeoPoint:(id<OrgOsmdroidApiIGeoPoint>)gp {
  if ((self = [super init])) {
    latitude_ = [((id<OrgOsmdroidApiIGeoPoint>) NIL_CHK(gp)) getLatitudeE6];
    longitude_ = [((id<OrgOsmdroidApiIGeoPoint>) NIL_CHK(gp)) getLongitudeE6];
  }
  return self;
}

- (int)getLatitudeE6 {
  return latitude_;
}

- (int)getLongitudeE6 {
  return longitude_;
}

- (id<OrgOsmdroidApiIGeoPoint>)toGeoPoint {
  return [[[ComAdironBusmeIntegrationGeoPoint alloc] initWithInt:latitude_ withInt:longitude_] autorelease];
}

- (void)dealloc {
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmePlatformGeoPointSerializable *typedCopy = (ComAdironBusmePlatformGeoPointSerializable *) copy;
  typedCopy.latitude = latitude_;
  typedCopy.longitude = longitude_;
}

@end
