//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/GeoPathUtils.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmeIntegrationGeoPoint;
@class IOSObjectArray;
@protocol JavaUtilList;
@protocol OrgOsmdroidApiIGeoPoint;

#import "JreEmulation.h"

#define ComAdironBusmePlatformGeoPathUtils_EARTH_RADIUS_FEET 2.090226116756E7
#define ComAdironBusmePlatformGeoPathUtils_FEET_PER_KM 3280.84
#define ComAdironBusmePlatformGeoPathUtils_LAT_PER_FOT 2.738129E-6
#define ComAdironBusmePlatformGeoPathUtils_LON_PER_FOOT 2.738015E-6

@interface ComAdironBusmePlatformGeoPathUtils : NSObject {
}

+ (double)LAT_PER_FOT;
+ (double)LON_PER_FOOT;
+ (double)FEET_PER_KM;
+ (double)EARTH_RADIUS_FEET;
+ (double)getCentralAngleWithOrgOsmdroidApiIGeoPoint:(id<OrgOsmdroidApiIGeoPoint>)c1
                         withOrgOsmdroidApiIGeoPoint:(id<OrgOsmdroidApiIGeoPoint>)iGeoPoint;
+ (double)getGeoAngleWithOrgOsmdroidApiIGeoPoint:(id<OrgOsmdroidApiIGeoPoint>)c1
                     withOrgOsmdroidApiIGeoPoint:(id<OrgOsmdroidApiIGeoPoint>)iGeoPoint;
+ (double)getGeoDistanceWithOrgOsmdroidApiIGeoPoint:(id<OrgOsmdroidApiIGeoPoint>)c1
                        withOrgOsmdroidApiIGeoPoint:(id<OrgOsmdroidApiIGeoPoint>)iGeoPoint;
+ (BOOL)onLineWithOrgOsmdroidApiIGeoPoint:(id<OrgOsmdroidApiIGeoPoint>)c1
              withOrgOsmdroidApiIGeoPoint:(id<OrgOsmdroidApiIGeoPoint>)c2
                               withDouble:(double)buffer
              withOrgOsmdroidApiIGeoPoint:(id<OrgOsmdroidApiIGeoPoint>)iGeoPoint;
+ (BOOL)isOnPathWithOrgOsmdroidApiIGeoPointArray:(IOSObjectArray *)path
                     withOrgOsmdroidApiIGeoPoint:(id<OrgOsmdroidApiIGeoPoint>)iGeoPoint
                                      withDouble:(double)buffer;
+ (id<JavaUtilList>)whereOnPathWithOrgOsmdroidApiIGeoPointArray:(IOSObjectArray *)path
                          withComAdironBusmeIntegrationGeoPoint:(ComAdironBusmeIntegrationGeoPoint *)point
                                                     withDouble:(double)buffer;
+ (double)getDistanceWithComAdironBusmeIntegrationGeoPointArray:(IOSObjectArray *)path;
- (id)init;
@end

@interface ComAdironBusmePlatformGeoPathUtils_DGeoPoint : NSObject {
 @public
  ComAdironBusmeIntegrationGeoPoint *point_;
  double bearing_;
  double distance_;
}

@property (nonatomic, retain) ComAdironBusmeIntegrationGeoPoint *point;
@property (nonatomic, assign) double bearing;
@property (nonatomic, assign) double distance;

- (id)initWithComAdironBusmeIntegrationGeoPoint:(ComAdironBusmeIntegrationGeoPoint *)point
                                     withDouble:(double)distance
                                     withDouble:(double)bearing;
@end
