//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/Handler.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/integration/Handler.h"
#import "com/adiron/busme/platform/Handler.h"
#import "java/lang/Runnable.h"

@implementation ComAdironBusmePlatformHandler

- (ComAdironBusmeIntegrationHandler *)delegate {
  return delegate_;
}
- (void)setDelegate:(ComAdironBusmeIntegrationHandler *)delegate {
  JreOperatorRetainedAssign(&delegate_, delegate);
}
@synthesize delegate = delegate_;

- (BOOL)postWithJavaLangRunnable:(id<JavaLangRunnable>)r {
  return [((ComAdironBusmeIntegrationHandler *) NIL_CHK(delegate_)) postWithJavaLangRunnable:r];
}

- (BOOL)postAtFrontOfQueueWithJavaLangRunnable:(id<JavaLangRunnable>)r {
  return [((ComAdironBusmeIntegrationHandler *) NIL_CHK(delegate_)) postAtFrontOfQueueWithJavaLangRunnable:r];
}

- (BOOL)postDelayedWithJavaLangRunnable:(id<JavaLangRunnable>)r
                            withLongInt:(long long int)delayMillis {
  return [((ComAdironBusmeIntegrationHandler *) NIL_CHK(delegate_)) postDelayedWithJavaLangRunnable:r withLongInt:delayMillis];
}

- (void)removeCallbacksWithJavaLangRunnable:(id<JavaLangRunnable>)r
                                     withId:(id)token {
  [((ComAdironBusmeIntegrationHandler *) NIL_CHK(delegate_)) removeCallbacksWithJavaLangRunnable:r withId:token];
}

- (void)removeCallbacksWithJavaLangRunnable:(id<JavaLangRunnable>)r {
  [((ComAdironBusmeIntegrationHandler *) NIL_CHK(delegate_)) removeCallbacksWithJavaLangRunnable:r];
}

- (id)init {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&delegate_, [[[ComAdironBusmeIntegrationHandler alloc] init] autorelease]);
  }
  return self;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&delegate_, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmePlatformHandler *typedCopy = (ComAdironBusmePlatformHandler *) copy;
  typedCopy.delegate = delegate_;
}

@end
