//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/JourneyBasket.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmeApiJourneyPattern;
@class ComAdironBusmeApiNameId;
@class ComAdironBusmeApiRoute;
@class ComAdironBusmePlatformActivityAPI;
@class ComAdironBusmePlatformJourneyStore;
@class JavaIoIOException;
@protocol ComAdironBusmePlatformJourneyBasket_OnBasketUpdateListener;
@protocol ComAdironBusmePlatformJourneyBasket_OnIOErrorListener;
@protocol ComAdironBusmePlatformJourneyBasket_OnJourneyAddedListener;
@protocol ComAdironBusmePlatformJourneyBasket_OnJourneyRemovedListener;
@protocol ComAdironBusmePlatformJourneyBasket_ProgressListener;
@protocol JavaUtilList;
@protocol JavaUtilMap;

#import "JreEmulation.h"

@interface ComAdironBusmePlatformJourneyBasket : NSObject {
 @public
  ComAdironBusmePlatformActivityAPI *activityAPI_;
  id<JavaUtilList> journeys_;
  ComAdironBusmePlatformJourneyStore *journeyStore_;
  id<JavaUtilMap> journeyMap_;
  id<ComAdironBusmePlatformJourneyBasket_OnJourneyAddedListener> onJourneyAddedListener_;
  id<ComAdironBusmePlatformJourneyBasket_OnJourneyRemovedListener> onJourneyRemovedListener_;
  id<ComAdironBusmePlatformJourneyBasket_OnBasketUpdateListener> onBasketUpdateListener_;
}

@property (nonatomic, retain) ComAdironBusmePlatformActivityAPI *activityAPI;
@property (nonatomic, retain) id<JavaUtilList> journeys;
@property (nonatomic, retain) ComAdironBusmePlatformJourneyStore *journeyStore;
@property (nonatomic, retain) id<JavaUtilMap> journeyMap;
@property (nonatomic, retain) id<ComAdironBusmePlatformJourneyBasket_OnJourneyAddedListener> onJourneyAddedListener;
@property (nonatomic, retain) id<ComAdironBusmePlatformJourneyBasket_OnJourneyRemovedListener> onJourneyRemovedListener;
@property (nonatomic, retain) id<ComAdironBusmePlatformJourneyBasket_OnBasketUpdateListener> onBasketUpdateListener;

+ (NSString *)LOGTAG;
- (id)initWithComAdironBusmePlatformActivityAPI:(ComAdironBusmePlatformActivityAPI *)api
         withComAdironBusmePlatformJourneyStore:(ComAdironBusmePlatformJourneyStore *)journeyStore;
- (ComAdironBusmeApiRoute *)retrieveRouteWithComAdironBusmeApiNameId:(ComAdironBusmeApiNameId *)id_;
- (ComAdironBusmeApiJourneyPattern *)retrieveJourneyPatternWithNSString:(NSString *)id_;
- (ComAdironBusmeApiRoute *)retrieveWithComAdironBusmeApiNameId:(ComAdironBusmeApiNameId *)id_;
- (void)syncWithJavaUtilList:(id<JavaUtilList>)journeyids
withComAdironBusmePlatformJourneyBasket_ProgressListener:(id<ComAdironBusmePlatformJourneyBasket_ProgressListener>)progressListener
withComAdironBusmePlatformJourneyBasket_OnIOErrorListener:(id<ComAdironBusmePlatformJourneyBasket_OnIOErrorListener>)onIOErrorListener;
- (void)setJourneysWithJavaUtilList:(id<JavaUtilList>)journeys;
- (void)updateJourneyMap;
- (ComAdironBusmeApiRoute *)getRouteWithNSString:(NSString *)id_;
- (id<JavaUtilList>)getAllRoutes;
- (id<JavaUtilList>)getAllJourneys;
- (id<JavaUtilList>)getAllActiveJourneys;
- (void)empty;
- (void)removeAllJourneys;
- (id<ComAdironBusmePlatformJourneyBasket_OnJourneyAddedListener>)getOnJourneyAddedListener;
- (void)setOnJourneyAddedListenerWithComAdironBusmePlatformJourneyBasket_OnJourneyAddedListener:(id<ComAdironBusmePlatformJourneyBasket_OnJourneyAddedListener>)onJourneyAddedListener;
- (id<ComAdironBusmePlatformJourneyBasket_OnJourneyRemovedListener>)getOnJourneyRemovedListener;
- (void)setOnJourneyRemovedListenerWithComAdironBusmePlatformJourneyBasket_OnJourneyRemovedListener:(id<ComAdironBusmePlatformJourneyBasket_OnJourneyRemovedListener>)onJourneyRemovedListener;
- (id<ComAdironBusmePlatformJourneyBasket_OnBasketUpdateListener>)getOnBasketUpdateListener;
- (void)setOnBasketUpdateListenerWithComAdironBusmePlatformJourneyBasket_OnBasketUpdateListener:(id<ComAdironBusmePlatformJourneyBasket_OnBasketUpdateListener>)onBasketUpdateListener;
- (void)notifyBasketUpdateListener;
- (void)notifyJourneyAddedListenerWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)added;
- (void)notifyJourneyRemovedListenerWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)removed;
- (void)dealloc;
@end

@protocol ComAdironBusmePlatformJourneyBasket_ProgressListener < NSObject >
- (void)onSyncStart;
- (void)onSyncEndWithInt:(int)nRoutes;
- (void)onRouteStartWithInt:(int)iRoute;
- (void)onRouteEndWithInt:(int)iRoute;
- (void)onDone;
@end

@protocol ComAdironBusmePlatformJourneyBasket_OnIOErrorListener < NSObject >
- (void)onIOErrorWithComAdironBusmePlatformJourneyBasket:(ComAdironBusmePlatformJourneyBasket *)basket
                                   withJavaIoIOException:(JavaIoIOException *)e;
@end

@protocol ComAdironBusmePlatformJourneyBasket_OnJourneyAddedListener < NSObject >
- (void)onJourneyAddedWithComAdironBusmePlatformJourneyBasket:(ComAdironBusmePlatformJourneyBasket *)basket
                                   withComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)added;
@end

@protocol ComAdironBusmePlatformJourneyBasket_OnJourneyRemovedListener < NSObject >
- (void)onJourneyRemovedWithComAdironBusmePlatformJourneyBasket:(ComAdironBusmePlatformJourneyBasket *)basket
                                     withComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)removed;
@end

@protocol ComAdironBusmePlatformJourneyBasket_OnBasketUpdateListener < NSObject >
- (void)onUpdateBasketWithComAdironBusmePlatformJourneyBasket:(ComAdironBusmePlatformJourneyBasket *)basket;
@end
