//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/JourneyBasketController.java
//
//  Created by polar on 5/25/13.
//

#import "IOSClass.h"
#import "IOSObjectArray.h"
#import "com/adiron/busme/api/Route.h"
#import "com/adiron/busme/platform/ActivityAPI.h"
#import "com/adiron/busme/platform/BusmeActivityController.h"
#import "com/adiron/busme/platform/DisplayPlaneModelController.h"
#import "com/adiron/busme/platform/JourneyBasket.h"
#import "com/adiron/busme/platform/JourneyBasketController.h"
#import "com/adiron/busme/platform/JourneyDisplay.h"
#import "com/adiron/busme/platform/Log.h"
#import "java/util/ArrayList.h"
#import "java/util/HashMap.h"
#import "java/util/List.h"
#import "java/util/Map.h"

@implementation ComAdironBusmePlatformJourneyBasketController

static NSString * ComAdironBusmePlatformJourneyBasketController_LOGTAG_;

- (ComAdironBusmePlatformActivityAPI *)activityAPI {
  return activityAPI_;
}
- (void)setActivityAPI:(ComAdironBusmePlatformActivityAPI *)activityAPI {
  JreOperatorRetainedAssign(&activityAPI_, activityAPI);
}
@synthesize activityAPI = activityAPI_;
- (ComAdironBusmePlatformBusmeActivityController *)busmeActivityController {
  return busmeActivityController_;
}
- (void)setBusmeActivityController:(ComAdironBusmePlatformBusmeActivityController *)busmeActivityController {
  JreOperatorRetainedAssign(&busmeActivityController_, busmeActivityController);
}
@synthesize busmeActivityController = busmeActivityController_;
- (id<JavaUtilList>)journeyDisplays {
  return journeyDisplays_;
}
- (void)setJourneyDisplays:(id<JavaUtilList>)journeyDisplays {
  JreOperatorRetainedAssign(&journeyDisplays_, journeyDisplays);
}
@synthesize journeyDisplays = journeyDisplays_;
- (ComAdironBusmePlatformJourneyBasket *)journeyBasket {
  return journeyBasket_;
}
- (void)setJourneyBasket:(ComAdironBusmePlatformJourneyBasket *)journeyBasket {
  JreOperatorRetainedAssign(&journeyBasket_, journeyBasket);
}
@synthesize journeyBasket = journeyBasket_;
@synthesize please_stop = please_stop_;
@synthesize updateInProgress = updateInProgress_;
@synthesize doNotRemoveJourneys = doNotRemoveJourneys_;
- (id<ComAdironBusmePlatformJourneyBasketController_OnJourneyDisplayAddedListener>)onJourneyDisplayAddedListener {
  return onJourneyDisplayAddedListener_;
}
- (void)setOnJourneyDisplayAddedListener:(id<ComAdironBusmePlatformJourneyBasketController_OnJourneyDisplayAddedListener>)onJourneyDisplayAddedListener {
  JreOperatorRetainedAssign(&onJourneyDisplayAddedListener_, onJourneyDisplayAddedListener);
}
@synthesize onJourneyDisplayAddedListener = onJourneyDisplayAddedListener_;
- (id<ComAdironBusmePlatformJourneyBasketController_OnJourneyDisplayRemovedListener>)onJourneyDisplayRemovedListener {
  return onJourneyDisplayRemovedListener_;
}
- (void)setOnJourneyDisplayRemovedListener:(id<ComAdironBusmePlatformJourneyBasketController_OnJourneyDisplayRemovedListener>)onJourneyDisplayRemovedListener {
  JreOperatorRetainedAssign(&onJourneyDisplayRemovedListener_, onJourneyDisplayRemovedListener);
}
@synthesize onJourneyDisplayRemovedListener = onJourneyDisplayRemovedListener_;
- (id<JavaUtilMap>)journeyDisplayMap {
  return journeyDisplayMap_;
}
- (void)setJourneyDisplayMap:(id<JavaUtilMap>)journeyDisplayMap {
  JreOperatorRetainedAssign(&journeyDisplayMap_, journeyDisplayMap);
}
@synthesize journeyDisplayMap = journeyDisplayMap_;
- (id<ComAdironBusmePlatformJourneyBasket_OnJourneyAddedListener>)onJourneyAddedListener {
  return onJourneyAddedListener_;
}
- (void)setOnJourneyAddedListener:(id<ComAdironBusmePlatformJourneyBasket_OnJourneyAddedListener>)onJourneyAddedListener {
  JreOperatorRetainedAssign(&onJourneyAddedListener_, onJourneyAddedListener);
}
@synthesize onJourneyAddedListener = onJourneyAddedListener_;
- (id<ComAdironBusmePlatformJourneyBasket_OnJourneyRemovedListener>)onJourneyRemovedListener {
  return onJourneyRemovedListener_;
}
- (void)setOnJourneyRemovedListener:(id<ComAdironBusmePlatformJourneyBasket_OnJourneyRemovedListener>)onJourneyRemovedListener {
  JreOperatorRetainedAssign(&onJourneyRemovedListener_, onJourneyRemovedListener);
}
@synthesize onJourneyRemovedListener = onJourneyRemovedListener_;
- (id<ComAdironBusmePlatformJourneyBasketController_OnUpdateListener>)onUpdateListener {
  return onUpdateListener_;
}
- (void)setOnUpdateListener:(id<ComAdironBusmePlatformJourneyBasketController_OnUpdateListener>)onUpdateListener {
  JreOperatorRetainedAssign(&onUpdateListener_, onUpdateListener);
}
@synthesize onUpdateListener = onUpdateListener_;
- (id<ComAdironBusmePlatformJourneyBasket_OnBasketUpdateListener>)onJourneyBasketUpdateListener {
  return onJourneyBasketUpdateListener_;
}
- (void)setOnJourneyBasketUpdateListener:(id<ComAdironBusmePlatformJourneyBasket_OnBasketUpdateListener>)onJourneyBasketUpdateListener {
  JreOperatorRetainedAssign(&onJourneyBasketUpdateListener_, onJourneyBasketUpdateListener);
}
@synthesize onJourneyBasketUpdateListener = onJourneyBasketUpdateListener_;

+ (NSString *)LOGTAG {
  return ComAdironBusmePlatformJourneyBasketController_LOGTAG_;
}

- (ComAdironBusmePlatformJourneyBasket *)getJourneyBasket {
  return journeyBasket_;
}

- (id)initWithComAdironBusmePlatformActivityAPI:(ComAdironBusmePlatformActivityAPI *)api
withComAdironBusmePlatformBusmeActivityController:(ComAdironBusmePlatformBusmeActivityController *)controller
        withComAdironBusmePlatformJourneyBasket:(ComAdironBusmePlatformJourneyBasket *)rl {
  if ((self = [super init])) {
    please_stop_ = NO;
    updateInProgress_ = NO;
    doNotRemoveJourneys_ = NO;
    JreOperatorRetainedAssign(&journeyDisplayMap_, [[[JavaUtilHashMap alloc] init] autorelease]);
    JreOperatorRetainedAssign(&onJourneyAddedListener_, [[[ComAdironBusmePlatformJourneyBasketController_$1 alloc] initWithComAdironBusmePlatformJourneyBasketController:self] autorelease]);
    JreOperatorRetainedAssign(&onJourneyRemovedListener_, [[[ComAdironBusmePlatformJourneyBasketController_$2 alloc] initWithComAdironBusmePlatformJourneyBasketController:self] autorelease]);
    JreOperatorRetainedAssign(&onJourneyBasketUpdateListener_, [[[ComAdironBusmePlatformJourneyBasketController_$3 alloc] initWithComAdironBusmePlatformJourneyBasketController:self] autorelease]);
    self.activityAPI = api;
    self.journeyDisplays = [[[JavaUtilArrayList alloc] init] autorelease];
    self.journeyBasket = rl;
    self.busmeActivityController = controller;
  }
  return self;
}

- (id<JavaUtilList>)getJourneyDisplays {
  return journeyDisplays_;
}

- (id<JavaUtilList>)getAllRoutes {
  return [((ComAdironBusmePlatformJourneyBasket *) NIL_CHK(journeyBasket_)) getAllRoutes];
}

- (id<JavaUtilList>)getAllActiveJourneys {
  return [((ComAdironBusmePlatformJourneyBasket *) NIL_CHK(journeyBasket_)) getAllActiveJourneys];
}

- (id<JavaUtilList>)getAllJourneys {
  return [((ComAdironBusmePlatformJourneyBasket *) NIL_CHK(journeyBasket_)) getAllJourneys];
}

- (void)setOnJourneyDisplayAddedListenerWithComAdironBusmePlatformJourneyBasketController_OnJourneyDisplayAddedListener:(id<ComAdironBusmePlatformJourneyBasketController_OnJourneyDisplayAddedListener>)onJourneyDisplayAddedListener {
  self.onJourneyDisplayAddedListener = onJourneyDisplayAddedListener;
}

- (void)setOnJourneyDisplayRemovedListenerWithComAdironBusmePlatformJourneyBasketController_OnJourneyDisplayRemovedListener:(id<ComAdironBusmePlatformJourneyBasketController_OnJourneyDisplayRemovedListener>)onJourneyDisplayRemovedListener {
  self.onJourneyDisplayRemovedListener = onJourneyDisplayRemovedListener;
}

- (void)setOnUpdateListenerWithComAdironBusmePlatformJourneyBasketController_OnUpdateListener:(id<ComAdironBusmePlatformJourneyBasketController_OnUpdateListener>)onUpdateListener {
  self.onUpdateListener = onUpdateListener;
}

- (void)onCreate {
  [ComAdironBusmePlatformLog dWithNSString:ComAdironBusmePlatformJourneyBasketController_LOGTAG_ withNSString:@"onCreate"];
  JreOperatorRetainedAssign(&journeyDisplays_, [[[JavaUtilArrayList alloc] init] autorelease]);
  [((ComAdironBusmePlatformJourneyBasket *) NIL_CHK(journeyBasket_)) setOnJourneyAddedListenerWithComAdironBusmePlatformJourneyBasket_OnJourneyAddedListener:onJourneyAddedListener_];
  [((ComAdironBusmePlatformJourneyBasket *) NIL_CHK(journeyBasket_)) setOnJourneyRemovedListenerWithComAdironBusmePlatformJourneyBasket_OnJourneyRemovedListener:onJourneyRemovedListener_];
  [((ComAdironBusmePlatformJourneyBasket *) NIL_CHK(journeyBasket_)) setOnBasketUpdateListenerWithComAdironBusmePlatformJourneyBasket_OnBasketUpdateListener:onJourneyBasketUpdateListener_];
}

- (void)onLocationUpdateWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)route
                  withOrgOsmdroidApiIGeoPointArray:(IOSObjectArray *)locations {
  ComAdironBusmePlatformJourneyDisplay *jd = ((ComAdironBusmePlatformJourneyDisplay *) [((id<JavaUtilMap>) NIL_CHK(journeyDisplayMap_)) getWithId:[((ComAdironBusmeApiRoute *) NIL_CHK(route)) getId]]);
  [((ComAdironBusmePlatformJourneyDisplay *) NIL_CHK(jd)) onLocationUpdateWithComAdironBusmeApiRoute:route withOrgOsmdroidApiIGeoPointArray:locations];
}

+ (void)initialize {
  if (self == [ComAdironBusmePlatformJourneyBasketController class]) {
    JreOperatorRetainedAssign(&ComAdironBusmePlatformJourneyBasketController_LOGTAG_, [[IOSClass classWithClass:[ComAdironBusmePlatformJourneyBasketController class]] getName]);
  }
}

- (void)dealloc {
  JreOperatorRetainedAssign(&onJourneyBasketUpdateListener_, nil);
  JreOperatorRetainedAssign(&onUpdateListener_, nil);
  JreOperatorRetainedAssign(&onJourneyRemovedListener_, nil);
  JreOperatorRetainedAssign(&onJourneyAddedListener_, nil);
  JreOperatorRetainedAssign(&journeyDisplayMap_, nil);
  JreOperatorRetainedAssign(&onJourneyDisplayRemovedListener_, nil);
  JreOperatorRetainedAssign(&onJourneyDisplayAddedListener_, nil);
  JreOperatorRetainedAssign(&journeyBasket_, nil);
  JreOperatorRetainedAssign(&journeyDisplays_, nil);
  JreOperatorRetainedAssign(&busmeActivityController_, nil);
  JreOperatorRetainedAssign(&activityAPI_, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmePlatformJourneyBasketController *typedCopy = (ComAdironBusmePlatformJourneyBasketController *) copy;
  typedCopy.activityAPI = activityAPI_;
  typedCopy.busmeActivityController = busmeActivityController_;
  typedCopy.journeyDisplays = journeyDisplays_;
  typedCopy.journeyBasket = journeyBasket_;
  typedCopy.please_stop = please_stop_;
  typedCopy.updateInProgress = updateInProgress_;
  typedCopy.doNotRemoveJourneys = doNotRemoveJourneys_;
  typedCopy.onJourneyDisplayAddedListener = onJourneyDisplayAddedListener_;
  typedCopy.onJourneyDisplayRemovedListener = onJourneyDisplayRemovedListener_;
  typedCopy.journeyDisplayMap = journeyDisplayMap_;
  typedCopy.onJourneyAddedListener = onJourneyAddedListener_;
  typedCopy.onJourneyRemovedListener = onJourneyRemovedListener_;
  typedCopy.onUpdateListener = onUpdateListener_;
  typedCopy.onJourneyBasketUpdateListener = onJourneyBasketUpdateListener_;
}

@end
@implementation ComAdironBusmePlatformJourneyBasketController_$1

- (ComAdironBusmePlatformJourneyBasketController *)this$0 {
  return this$0_;
}
- (void)setThis$0:(ComAdironBusmePlatformJourneyBasketController *)this$0 {
  JreOperatorRetainedAssign(&this$0_, this$0);
}
@synthesize this$0 = this$0_;

- (void)onJourneyAddedWithComAdironBusmePlatformJourneyBasket:(ComAdironBusmePlatformJourneyBasket *)basket
                                   withComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)added {
  [ComAdironBusmePlatformLog dWithNSString:[ComAdironBusmePlatformJourneyBasketController LOGTAG] withNSString:[NSString stringWithFormat:@"onJourneyAdded:%@", [((ComAdironBusmeApiRoute *) NIL_CHK(added)) getName]]];
  ComAdironBusmePlatformJourneyDisplay *newRoute = [[[ComAdironBusmePlatformJourneyDisplay alloc] initWithComAdironBusmePlatformJourneyBasketController:this$0_ withComAdironBusmeApiRoute:added] autorelease];
  if (this$0_.onJourneyDisplayAddedListener != nil) {
    [this$0_.onJourneyDisplayAddedListener onJourneyDisplayAddedPreWithComAdironBusmePlatformJourneyBasketController:this$0_ withComAdironBusmePlatformJourneyBasket:basket withComAdironBusmePlatformJourneyDisplay:newRoute];
  }
  [[((ComAdironBusmePlatformBusmeActivityController *) NIL_CHK(this$0_.busmeActivityController)) getDisplayPlaneModelController] addJourneyDisplayWithComAdironBusmePlatformJourneyDisplay:newRoute];
  id<JavaUtilList> displays = [[[JavaUtilArrayList alloc] initWithJavaUtilCollection:this$0_.journeyDisplays] autorelease];
  [((id<JavaUtilList>) NIL_CHK(displays)) addWithId:newRoute];
  this$0_.journeyDisplays = displays;
  [((id<JavaUtilMap>) NIL_CHK(this$0_.journeyDisplayMap)) putWithId:[[((ComAdironBusmePlatformJourneyDisplay *) NIL_CHK(newRoute)) getRoute] getId] withId:newRoute];
  if (this$0_.onJourneyDisplayAddedListener != nil) {
    [this$0_.onJourneyDisplayAddedListener onJourneyDisplayAddedPostWithComAdironBusmePlatformJourneyBasketController:this$0_ withComAdironBusmePlatformJourneyBasket:basket withComAdironBusmePlatformJourneyDisplay:newRoute];
  }
}

- (id)initWithComAdironBusmePlatformJourneyBasketController:(ComAdironBusmePlatformJourneyBasketController *)outer$ {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&this$0_, outer$);
  }
  return self;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&this$0_, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmePlatformJourneyBasketController_$1 *typedCopy = (ComAdironBusmePlatformJourneyBasketController_$1 *) copy;
  typedCopy.this$0 = this$0_;
}

@end
@implementation ComAdironBusmePlatformJourneyBasketController_$2

- (ComAdironBusmePlatformJourneyBasketController *)this$0 {
  return this$0_;
}
- (void)setThis$0:(ComAdironBusmePlatformJourneyBasketController *)this$0 {
  JreOperatorRetainedAssign(&this$0_, this$0);
}
@synthesize this$0 = this$0_;

- (void)onJourneyRemovedWithComAdironBusmePlatformJourneyBasket:(ComAdironBusmePlatformJourneyBasket *)basket
                                     withComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)removed {
  [ComAdironBusmePlatformLog dWithNSString:[ComAdironBusmePlatformJourneyBasketController LOGTAG] withNSString:[NSString stringWithFormat:@"onJourneyRemoved:%@", [((ComAdironBusmeApiRoute *) NIL_CHK(removed)) getName]]];
  ComAdironBusmePlatformJourneyDisplay *rd = ((ComAdironBusmePlatformJourneyDisplay *) [((id<JavaUtilMap>) NIL_CHK(this$0_.journeyDisplayMap)) getWithId:[((ComAdironBusmeApiRoute *) NIL_CHK(removed)) getId]]);
  if (rd != nil) {
    if (this$0_.onJourneyDisplayRemovedListener != nil) {
      [this$0_.onJourneyDisplayRemovedListener onJourneyDisplayRemovedPreWithComAdironBusmePlatformJourneyBasketController:this$0_ withComAdironBusmePlatformJourneyBasket:basket withComAdironBusmePlatformJourneyDisplay:rd];
    }
    [[((ComAdironBusmePlatformBusmeActivityController *) NIL_CHK(this$0_.busmeActivityController)) getDisplayPlaneModelController] removeJourneyDisplayWithComAdironBusmePlatformJourneyDisplay:rd];
    [ComAdironBusmePlatformLog dWithNSString:[ComAdironBusmePlatformJourneyBasketController LOGTAG] withNSString:[NSString stringWithFormat:@"removing JourneyDisplay: Route %@ %qi = %@", [[rd getRoute] getName], [[rd getRoute] getVersion], [rd getRoute]]];
    id<JavaUtilList> displays = [[[JavaUtilArrayList alloc] initWithJavaUtilCollection:this$0_.journeyDisplays] autorelease];
    [((id<JavaUtilList>) NIL_CHK(displays)) removeWithId:rd];
    [((id<JavaUtilMap>) NIL_CHK(this$0_.journeyDisplayMap)) removeWithId:[[rd getRoute] getId]];
    this$0_.journeyDisplays = displays;
    if (this$0_.onJourneyDisplayRemovedListener != nil) {
      [this$0_.onJourneyDisplayRemovedListener onJourneyDisplayRemovedPostWithComAdironBusmePlatformJourneyBasketController:this$0_ withComAdironBusmePlatformJourneyBasket:basket withComAdironBusmePlatformJourneyDisplay:rd];
    }
  }
}

- (id)initWithComAdironBusmePlatformJourneyBasketController:(ComAdironBusmePlatformJourneyBasketController *)outer$ {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&this$0_, outer$);
  }
  return self;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&this$0_, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmePlatformJourneyBasketController_$2 *typedCopy = (ComAdironBusmePlatformJourneyBasketController_$2 *) copy;
  typedCopy.this$0 = this$0_;
}

@end
@implementation ComAdironBusmePlatformJourneyBasketController_$3

- (ComAdironBusmePlatformJourneyBasketController *)this$0 {
  return this$0_;
}
- (void)setThis$0:(ComAdironBusmePlatformJourneyBasketController *)this$0 {
  JreOperatorRetainedAssign(&this$0_, this$0);
}
@synthesize this$0 = this$0_;

- (void)onUpdateBasketWithComAdironBusmePlatformJourneyBasket:(ComAdironBusmePlatformJourneyBasket *)basket {
  [ComAdironBusmePlatformLog dWithNSString:[ComAdironBusmePlatformJourneyBasketController LOGTAG] withNSString:@"onUpdateBasket"];
  if (this$0_.onUpdateListener != nil) {
    [this$0_.onUpdateListener onUpdateWithComAdironBusmePlatformJourneyBasketController:this$0_];
  }
}

- (id)initWithComAdironBusmePlatformJourneyBasketController:(ComAdironBusmePlatformJourneyBasketController *)outer$ {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&this$0_, outer$);
  }
  return self;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&this$0_, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmePlatformJourneyBasketController_$3 *typedCopy = (ComAdironBusmePlatformJourneyBasketController_$3 *) copy;
  typedCopy.this$0 = this$0_;
}

@end
