//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/JourneyLocationPoster.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmeApiRoute;
@class ComAdironBusmePlatformActivityAPI;
@class ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_ReasonEnum;
@class ComAdironBusmePlatformLocation;
@class ComAdironBusmePlatformLocationManager;
@protocol ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener;

#import "JreEmulation.h"
#import "com/adiron/busme/platform/LocationListener.h"
#import "java/lang/Enum.h"

@interface ComAdironBusmePlatformJourneyLocationPoster : NSObject < ComAdironBusmePlatformLocationListener > {
 @public
  ComAdironBusmePlatformActivityAPI *activityAPI_;
  ComAdironBusmePlatformLocationManager *locationManager_;
  ComAdironBusmeApiRoute *postingRoute_;
  NSString *postingRole_;
  int offRouteCount_;
  long long int offRouteTime_;
  id<ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener> routeEventListener_;
  BOOL alreadyPosting_;
  BOOL alreadyStarted_;
  int gpsLocationStatus_;
  BOOL enabled_;
  BOOL alreadyFinished_;
}

@property (nonatomic, retain) ComAdironBusmePlatformActivityAPI *activityAPI;
@property (nonatomic, retain) ComAdironBusmePlatformLocationManager *locationManager;
@property (nonatomic, retain) ComAdironBusmeApiRoute *postingRoute;
@property (nonatomic, copy) NSString *postingRole;
@property (nonatomic, assign) int offRouteCount;
@property (nonatomic, assign) long long int offRouteTime;
@property (nonatomic, retain) id<ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener> routeEventListener;
@property (nonatomic, assign) BOOL alreadyPosting;
@property (nonatomic, assign) BOOL alreadyStarted;
@property (nonatomic, assign) int gpsLocationStatus;
@property (nonatomic, assign) BOOL enabled;
@property (nonatomic, assign) BOOL alreadyFinished;

+ (NSString *)LOGTAG;
- (NSString *)getPostingRole;
- (id)initWithComAdironBusmePlatformActivityAPI:(ComAdironBusmePlatformActivityAPI *)api
                     withComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)route
                                   withNSString:(NSString *)role;
- (void)endPosting;
- (void)endPostingNotifyWithComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_ReasonEnum:(ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_ReasonEnum *)reason;
- (void)setOnRouteEventListenerWithComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener:(id<ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener>)onRouteEventListener;
- (void)notifyOffRouteEventWithComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)loc;
- (void)notifyFinishedRouteEvent;
- (void)notifyStartedRouteEvent;
- (void)notifyUpdatedRouteEventWithComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)loc;
- (void)notifyOnRoutePosting;
- (void)notifyOnRouteDoneWithComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_ReasonEnum:(ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_ReasonEnum *)reason;
- (void)onLocationChangedWithComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)location;
- (void)onProviderDisabledWithNSString:(NSString *)provider;
- (void)onProviderEnabledWithNSString:(NSString *)provider;
- (void)onStatusChangedWithNSString:(NSString *)provider
                            withInt:(int)status;
- (ComAdironBusmeApiRoute *)getPostingRoute;
- (void)setPostingRouteWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)postingRoute;
@end

@protocol ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener < NSObject >
- (void)onRoutePostingWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)r;
- (void)atRouteStartWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)r;
- (void)onOffRouteEventWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)r
               withComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)loc;
- (void)onOnRouteEventWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)r
              withComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)loc;
- (void)atRouteEndWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)r;
- (void)onRouteDoneWithComAdironBusmeApiRoute:(ComAdironBusmeApiRoute *)r
withComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_ReasonEnum:(ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_ReasonEnum *)reason;
@end

typedef enum {
  ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_Reason_NORMAL = 0,
  ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_Reason_FORCED = 1,
  ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_Reason_DISABLED = 2,
  ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_Reason_SERVICE = 3,
  ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_Reason_OFF_ROUTE = 4,
} ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_Reason;

@interface ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_ReasonEnum : JavaLangEnum < NSCopying > {
}
+ (ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_ReasonEnum *)NORMAL;
+ (ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_ReasonEnum *)FORCED;
+ (ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_ReasonEnum *)DISABLED;
+ (ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_ReasonEnum *)SERVICE;
+ (ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_ReasonEnum *)OFF_ROUTE;
+ (IOSObjectArray *)values;
+ (ComAdironBusmePlatformJourneyLocationPoster_OnRouteEventListener_ReasonEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;
- (id)initWithNSString:(NSString *)name withInt:(int)ordinal;
@end
