//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/JourneysSyncRequestProcessor.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmeApiAPIBase_Tag;
@protocol ComAdironBusmePlatformJourneysSyncRequestProcessor_OnJourneysSyncResponseListener;
@protocol JavaUtilList;

#import "JreEmulation.h"
#import "com/adiron/busme/platform/RequestUpdater.h"

@interface ComAdironBusmePlatformJourneysSyncRequestProcessor : NSObject < ComAdironBusmePlatformRequestUpdater_ArgumentsPreparer, ComAdironBusmePlatformRequestUpdater_ResponseProcessor > {
 @public
  id<JavaUtilList> emptyList_;
  id<ComAdironBusmePlatformJourneysSyncRequestProcessor_OnJourneysSyncResponseListener> onJourneysSyncResponseListener_;
}

@property (nonatomic, retain) id<JavaUtilList> emptyList;
@property (nonatomic, retain) id<ComAdironBusmePlatformJourneysSyncRequestProcessor_OnJourneysSyncResponseListener> onJourneysSyncResponseListener;

- (id)initWithComAdironBusmePlatformJourneysSyncRequestProcessor_OnJourneysSyncResponseListener:(id<ComAdironBusmePlatformJourneysSyncRequestProcessor_OnJourneysSyncResponseListener>)onJourneysSyncResponseListener;
- (void)processResponseWithComAdironBusmeApiAPIBase_Tag:(ComAdironBusmeApiAPIBase_Tag *)response;
- (id<JavaUtilList>)getArguments;
- (id<ComAdironBusmePlatformJourneysSyncRequestProcessor_OnJourneysSyncResponseListener>)getOnJourneysSyncResponseListener;
- (void)setOnJourneysSyncResponseListenerWithComAdironBusmePlatformJourneysSyncRequestProcessor_OnJourneysSyncResponseListener:(id<ComAdironBusmePlatformJourneysSyncRequestProcessor_OnJourneysSyncResponseListener>)onJourneysSyncResponseListener;
@end

@protocol ComAdironBusmePlatformJourneysSyncRequestProcessor_OnJourneysSyncResponseListener < NSObject >
- (void)onJourneysSyncResponseWithJavaUtilList:(id<JavaUtilList>)nameids;
@end
