//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/JourneysSyncRequestProcessor.java
//
//  Created by polar on 5/25/13.
//

#import "IOSObjectArray.h"
#import "com/adiron/busme/api/APIBase.h"
#import "com/adiron/busme/api/NameId.h"
#import "com/adiron/busme/platform/JourneysSyncRequestProcessor.h"
#import "java/util/ArrayList.h"
#import "java/util/Iterator.h"
#import "java/util/List.h"

@implementation ComAdironBusmePlatformJourneysSyncRequestProcessor

- (id<JavaUtilList>)emptyList {
  return emptyList_;
}
- (void)setEmptyList:(id<JavaUtilList>)emptyList {
  JreOperatorRetainedAssign(&emptyList_, emptyList);
}
@synthesize emptyList = emptyList_;
- (id<ComAdironBusmePlatformJourneysSyncRequestProcessor_OnJourneysSyncResponseListener>)onJourneysSyncResponseListener {
  return onJourneysSyncResponseListener_;
}
- (void)setOnJourneysSyncResponseListener:(id<ComAdironBusmePlatformJourneysSyncRequestProcessor_OnJourneysSyncResponseListener>)onJourneysSyncResponseListener {
  JreOperatorRetainedAssign(&onJourneysSyncResponseListener_, onJourneysSyncResponseListener);
}
@synthesize onJourneysSyncResponseListener = onJourneysSyncResponseListener_;

- (id)initWithComAdironBusmePlatformJourneysSyncRequestProcessor_OnJourneysSyncResponseListener:(id<ComAdironBusmePlatformJourneysSyncRequestProcessor_OnJourneysSyncResponseListener>)onJourneysSyncResponseListener {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&emptyList_, [[[JavaUtilArrayList alloc] init] autorelease]);
    [self setOnJourneysSyncResponseListenerWithComAdironBusmePlatformJourneysSyncRequestProcessor_OnJourneysSyncResponseListener:onJourneysSyncResponseListener];
  }
  return self;
}

- (void)processResponseWithComAdironBusmeApiAPIBase_Tag:(ComAdironBusmeApiAPIBase_Tag *)response {
  id<JavaUtilList> nameids = [[[JavaUtilArrayList alloc] init] autorelease];
  if (response != nil && ((ComAdironBusmeApiAPIBase_Tag *) NIL_CHK(response)).childNodes != nil) {
    {
      id<JavaUtilIterator> iter__ = ((id<JavaUtilIterator>) [((id<JavaUtilList>) NIL_CHK(response.childNodes)) iterator]);
      while ([((id<JavaUtilIterator>) NIL_CHK(iter__)) hasNext]) {
        ComAdironBusmeApiAPIBase_Tag *tag = ((ComAdironBusmeApiAPIBase_Tag *) [((id<JavaUtilIterator>) NIL_CHK(iter__)) next]);
        if ([@"R" isEqual:((ComAdironBusmeApiAPIBase_Tag *) NIL_CHK(tag)).name]) {
          [((id<JavaUtilList>) NIL_CHK(nameids)) addWithId:[[[ComAdironBusmeApiNameId alloc] initWithNSStringArray:[NIL_CHK(tag.text) split:@","]] autorelease]];
        }
        else if ([@"J" isEqual:((ComAdironBusmeApiAPIBase_Tag *) NIL_CHK(tag)).name]) {
          [((id<JavaUtilList>) NIL_CHK(nameids)) addWithId:[[[ComAdironBusmeApiNameId alloc] initWithNSStringArray:[NIL_CHK(tag.text) split:@","]] autorelease]];
        }
      }
    }
  }
  id<ComAdironBusmePlatformJourneysSyncRequestProcessor_OnJourneysSyncResponseListener> lis = [self getOnJourneysSyncResponseListener];
  if (lis != nil) {
    [lis onJourneysSyncResponseWithJavaUtilList:nameids];
  }
}

- (id<JavaUtilList>)getArguments {
  return emptyList_;
}

- (id<ComAdironBusmePlatformJourneysSyncRequestProcessor_OnJourneysSyncResponseListener>)getOnJourneysSyncResponseListener {
  return onJourneysSyncResponseListener_;
}

- (void)setOnJourneysSyncResponseListenerWithComAdironBusmePlatformJourneysSyncRequestProcessor_OnJourneysSyncResponseListener:(id<ComAdironBusmePlatformJourneysSyncRequestProcessor_OnJourneysSyncResponseListener>)onJourneysSyncResponseListener {
  self.onJourneysSyncResponseListener = onJourneysSyncResponseListener;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&onJourneysSyncResponseListener_, nil);
  JreOperatorRetainedAssign(&emptyList_, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmePlatformJourneysSyncRequestProcessor *typedCopy = (ComAdironBusmePlatformJourneysSyncRequestProcessor *) copy;
  typedCopy.emptyList = emptyList_;
  typedCopy.onJourneysSyncResponseListener = onJourneysSyncResponseListener_;
}

@end
