//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/Keys.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/platform/Keys.h"


@implementation ComAdironBusmePlatformKeys

static NSString * ComAdironBusmePlatformKeys_KEY_PREFERENCE_VERSION_ = @"PreferenceVersion";
static NSString * ComAdironBusmePlatformKeys_KEY_MUNICIPALITY_URL_ = @"MunicipalityUrl";
static NSString * ComAdironBusmePlatformKeys_KEY_MUNICIPALITY_NAME_ = @"MunicpalityName";
static NSString * ComAdironBusmePlatformKeys_KEY_MUNICIPALITY_SLUG_ = @"MunicpalitySlug";
static NSString * ComAdironBusmePlatformKeys_KEY_MUNICIPALITIES_ = @"MunicipalityNames";
static NSString * ComAdironBusmePlatformKeys_KEY_MUNICIPALITY_URLS_ = @"MunicipalityUrls";
static NSString * ComAdironBusmePlatformKeys_KEY_MUNICIPALITY_LATITUDE_ = @"MunicipalityLatitude";
static NSString * ComAdironBusmePlatformKeys_KEY_MUNICIPALITY_LONGITUDE_ = @"MunicipalityLongitude";

+ (NSString *)KEY_PREFERENCE_VERSION {
  return ComAdironBusmePlatformKeys_KEY_PREFERENCE_VERSION_;
}

+ (NSString *)KEY_MUNICIPALITY_URL {
  return ComAdironBusmePlatformKeys_KEY_MUNICIPALITY_URL_;
}

+ (NSString *)KEY_MUNICIPALITY_NAME {
  return ComAdironBusmePlatformKeys_KEY_MUNICIPALITY_NAME_;
}

+ (NSString *)KEY_MUNICIPALITY_SLUG {
  return ComAdironBusmePlatformKeys_KEY_MUNICIPALITY_SLUG_;
}

+ (NSString *)KEY_MUNICIPALITIES {
  return ComAdironBusmePlatformKeys_KEY_MUNICIPALITIES_;
}

+ (NSString *)KEY_MUNICIPALITY_URLS {
  return ComAdironBusmePlatformKeys_KEY_MUNICIPALITY_URLS_;
}

+ (NSString *)KEY_MUNICIPALITY_LATITUDE {
  return ComAdironBusmePlatformKeys_KEY_MUNICIPALITY_LATITUDE_;
}

+ (NSString *)KEY_MUNICIPALITY_LONGITUDE {
  return ComAdironBusmePlatformKeys_KEY_MUNICIPALITY_LONGITUDE_;
}

@end
