//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/Keys.java
//
//  Created by polar on 5/25/13.
//

#import "JreEmulation.h"

@protocol ComAdironBusmePlatformKeys < NSObject >
@end

@interface ComAdironBusmePlatformKeys : NSObject {
}
+ (NSString *)KEY_PREFERENCE_VERSION;
+ (NSString *)KEY_MUNICIPALITY_URL;
+ (NSString *)KEY_MUNICIPALITY_NAME;
+ (NSString *)KEY_MUNICIPALITY_SLUG;
+ (NSString *)KEY_MUNICIPALITIES;
+ (NSString *)KEY_MUNICIPALITY_URLS;
+ (NSString *)KEY_MUNICIPALITY_LATITUDE;
+ (NSString *)KEY_MUNICIPALITY_LONGITUDE;
@end
