//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/Location.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/integration/Location.h"
#import "com/adiron/busme/platform/Location.h"

@implementation ComAdironBusmePlatformLocation

- (ComAdironBusmeIntegrationLocation *)delegate {
  return delegate_;
}
- (void)setDelegate:(ComAdironBusmeIntegrationLocation *)delegate {
  JreOperatorRetainedAssign(&delegate_, delegate);
}
@synthesize delegate = delegate_;

- (id)initComAdironBusmePlatformLocationWithComAdironBusmeIntegrationLocation:(ComAdironBusmeIntegrationLocation *)d {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&delegate_, d);
  }
  return self;
}

- (id)initWithComAdironBusmeIntegrationLocation:(ComAdironBusmeIntegrationLocation *)d {
  return [self initComAdironBusmePlatformLocationWithComAdironBusmeIntegrationLocation:d];
}

- (id)initWithNSString:(NSString *)name {
  return [self initComAdironBusmePlatformLocationWithComAdironBusmeIntegrationLocation:[[[ComAdironBusmeIntegrationLocation alloc] initWithNSString:name] autorelease]];
}

- (float)bearingToWithComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)dest {
  return [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) bearingToWithComAdironBusmeIntegrationLocation:((ComAdironBusmePlatformLocation *) NIL_CHK(dest)).delegate];
}

- (int)describeContents {
  return [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) describeContents];
}

- (float)distanceToWithComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)dest {
  return [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) distanceToWithComAdironBusmeIntegrationLocation:((ComAdironBusmePlatformLocation *) NIL_CHK(dest)).delegate];
}

- (BOOL)isEqual:(id)o {
  return [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) isEqual:o];
}

- (float)getAccuracy {
  return [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) getAccuracy];
}

- (double)getAltitude {
  return [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) getAltitude];
}

- (float)getBearing {
  return [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) getBearing];
}

- (double)getLatitude {
  return [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) getLatitude];
}

- (double)getLongitude {
  return [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) getLongitude];
}

- (NSString *)getProvider {
  return [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) getProvider];
}

- (float)getSpeed {
  return [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) getSpeed];
}

- (long long int)getTime {
  return [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) getTime];
}

- (BOOL)hasAccuracy {
  return [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) hasAccuracy];
}

- (BOOL)hasAltitude {
  return [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) hasAltitude];
}

- (BOOL)hasBearing {
  return [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) hasBearing];
}

- (BOOL)hasSpeed {
  return [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) hasSpeed];
}

- (NSUInteger)hash {
  return [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) hash];
}

- (void)removeAccuracy {
  [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) removeAccuracy];
}

- (void)removeAltitude {
  [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) removeAltitude];
}

- (void)removeBearing {
  [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) removeBearing];
}

- (void)removeSpeed {
  [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) removeSpeed];
}

- (void)reset {
  [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) reset];
}

- (void)setWithComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)l {
  [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) setWithComAdironBusmeIntegrationLocation:((ComAdironBusmePlatformLocation *) NIL_CHK(l)).delegate];
}

- (void)setAccuracyWithFloat:(float)accuracy {
  [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) setAccuracyWithFloat:accuracy];
}

- (void)setAltitudeWithDouble:(double)altitude {
  [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) setAltitudeWithDouble:altitude];
}

- (void)setBearingWithFloat:(float)bearing {
  [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) setBearingWithFloat:bearing];
}

- (void)setLatitudeWithDouble:(double)latitude {
  [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) setLatitudeWithDouble:latitude];
}

- (void)setLongitudeWithDouble:(double)longitude {
  [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) setLongitudeWithDouble:longitude];
}

- (void)setProviderWithNSString:(NSString *)provider {
  [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) setProviderWithNSString:provider];
}

- (void)setSpeedWithFloat:(float)speed {
  [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) setSpeedWithFloat:speed];
}

- (void)setTimeWithLongInt:(long long int)time {
  [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) setTimeWithLongInt:time];
}

- (NSString *)description {
  return [((ComAdironBusmeIntegrationLocation *) NIL_CHK(delegate_)) description];
}

- (void)dealloc {
  JreOperatorRetainedAssign(&delegate_, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmePlatformLocation *typedCopy = (ComAdironBusmePlatformLocation *) copy;
  typedCopy.delegate = delegate_;
}

@end
