//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/LocationProvider.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/integration/LocationProvider.h"
#import "com/adiron/busme/platform/LocationProvider.h"

@implementation ComAdironBusmePlatformLocationProvider

+ (int)OUT_OF_SERVICE {
  return ComAdironBusmePlatformLocationProvider_OUT_OF_SERVICE;
}

+ (int)AVAILABLE {
  return ComAdironBusmePlatformLocationProvider_AVAILABLE;
}

+ (int)TEMPORARILY_UNAVAILABLE {
  return ComAdironBusmePlatformLocationProvider_TEMPORARILY_UNAVAILABLE;
}

- (id)init {
  return [super init];
}

- (void)dealloc {
  [super dealloc];
}

@end
