//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/Location.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmeIntegrationLocation;

#import "JreEmulation.h"

@interface ComAdironBusmePlatformLocation : NSObject {
 @public
  ComAdironBusmeIntegrationLocation *delegate_;
}

@property (nonatomic, retain) ComAdironBusmeIntegrationLocation *delegate;

- (id)initWithComAdironBusmeIntegrationLocation:(ComAdironBusmeIntegrationLocation *)d;
- (id)initWithNSString:(NSString *)name;
- (float)bearingToWithComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)dest;
- (int)describeContents;
- (float)distanceToWithComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)dest;
- (BOOL)isEqual:(id)o;
- (float)getAccuracy;
- (double)getAltitude;
- (float)getBearing;
- (double)getLatitude;
- (double)getLongitude;
- (NSString *)getProvider;
- (float)getSpeed;
- (long long int)getTime;
- (BOOL)hasAccuracy;
- (BOOL)hasAltitude;
- (BOOL)hasBearing;
- (BOOL)hasSpeed;
- (NSUInteger)hash;
- (void)removeAccuracy;
- (void)removeAltitude;
- (void)removeBearing;
- (void)removeSpeed;
- (void)reset;
- (void)setWithComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)l;
- (void)setAccuracyWithFloat:(float)accuracy;
- (void)setAltitudeWithDouble:(double)altitude;
- (void)setBearingWithFloat:(float)bearing;
- (void)setLatitudeWithDouble:(double)latitude;
- (void)setLongitudeWithDouble:(double)longitude;
- (void)setProviderWithNSString:(NSString *)provider;
- (void)setSpeedWithFloat:(float)speed;
- (void)setTimeWithLongInt:(long long int)time;
- (NSString *)description;
@end
