//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/LocationListener.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmePlatformLocation;

#import "JreEmulation.h"

@protocol ComAdironBusmePlatformLocationListener < NSObject >
- (void)onLocationChangedWithComAdironBusmePlatformLocation:(ComAdironBusmePlatformLocation *)location;
- (void)onProviderDisabledWithNSString:(NSString *)provider;
- (void)onStatusChangedWithNSString:(NSString *)provider
                            withInt:(int)status;
- (void)onProviderEnabledWithNSString:(NSString *)provider;
@end
