//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/LocationManager.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/integration/LocationManager.h"
#import "com/adiron/busme/platform/LocationManager.h"

@implementation ComAdironBusmePlatformLocationManager

static NSString * ComAdironBusmePlatformLocationManager_GPS_PROVIDER_ = "gps";

+ (NSString *)GPS_PROVIDER {
  return ComAdironBusmePlatformLocationManager_GPS_PROVIDER_;
}

- (id)init {
  return [super init];
}

- (void)dealloc {
  [super dealloc];
}

@end
