//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/LoginManager.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmeApiBuspassAPI_Login;
@class ComAdironBusmePlatformActivityAPI;
@class ComAdironBusmePlatformHandler;
@class ComAdironBusmePlatformLoginManager_LoginContinuation;
@class IOSObjectArray;
@protocol JavaUtilList;

#import "JreEmulation.h"
#import "com/adiron/busme/platform/LoginManager.h"
#import "java/lang/Runnable.h"

@interface ComAdironBusmePlatformLoginManager : NSObject {
 @public
  ComAdironBusmeApiBuspassAPI_Login *currentLogin_;
  NSString *currentAuthToken_;
  ComAdironBusmePlatformActivityAPI *activityAPI_;
}

@property (nonatomic, retain) ComAdironBusmeApiBuspassAPI_Login *currentLogin;
@property (nonatomic, copy) NSString *currentAuthToken;
@property (nonatomic, retain) ComAdironBusmePlatformActivityAPI *activityAPI;

+ (NSString *)LOGTAG;
+ (void)setLOGTAG:(NSString *)LOGTAG;
- (id)init;
- (void)dWithNSString:(NSString *)format
    withNSObjectArray:(IOSObjectArray *)args;
- (BOOL)isLoggedIn;
- (ComAdironBusmeApiBuspassAPI_Login *)getLogin;
- (void)forgetLogin;
- (void)setActivityAPIWithComAdironBusmePlatformActivityAPI:(ComAdironBusmePlatformActivityAPI *)activityAPI;
- (ComAdironBusmePlatformActivityAPI *)getActivityAPI;
- (ComAdironBusmePlatformHandler *)getBackgroundHandler;
- (ComAdironBusmePlatformHandler *)getUIHandler;
- (void)loginDriver;
- (void)loginPassenger;
- (void)ui_postLogin3WithNSString:(NSString *)roleIntent
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)success
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)failure;
- (void)launchLogin2WithNSString:(NSString *)roleIntent
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)success
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)failure;
- (void)onLocatorSelectedWithJavaUtilList:(id<JavaUtilList>)routes;
- (ComAdironBusmeApiBuspassAPI_Login *)performLoginIfNotLogggedInWithNSString:(NSString *)roleIntent
                     withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)success
                     withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)failure;
- (void)performAuthTokenLoginWithNSString:(NSString *)roleIntent
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)success
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)failure;
- (void)ui_postQuietLoginWithNSString:(NSString *)roleIntent
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)success
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)failure;
- (void)ui_postPasswordLoginWithNSString:(NSString *)roleIntent
                            withNSString:(NSString *)email
                            withNSString:(NSString *)password
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)success
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)failure;
- (void)ui_postRegistrationWithNSString:(NSString *)roleIntent
                           withNSString:(NSString *)email
                           withNSString:(NSString *)password
                           withNSString:(NSString *)driverAuthCode
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)success
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)failure;
- (void)ui_postLogout;
@end

@interface ComAdironBusmePlatformLoginManager_LoginContinuation : NSObject < JavaLangRunnable > {
 @public
  ComAdironBusmeApiBuspassAPI_Login *login_;
}

@property (nonatomic, retain) ComAdironBusmeApiBuspassAPI_Login *login;

- (void)setLoginWithComAdironBusmeApiBuspassAPI_Login:(ComAdironBusmeApiBuspassAPI_Login *)login;
- (ComAdironBusmeApiBuspassAPI_Login *)getLogin;
- (id)initWithComAdironBusmePlatformLoginManager:(ComAdironBusmePlatformLoginManager *)outer$;
@end

@interface ComAdironBusmePlatformLoginManager_DriverSuccessLoginContinuation : ComAdironBusmePlatformLoginManager_LoginContinuation {
 @public
  ComAdironBusmePlatformLoginManager *this$1_;
}

@property (nonatomic, retain) ComAdironBusmePlatformLoginManager *this$1;

- (void)run;
- (id)initWithComAdironBusmePlatformLoginManager:(ComAdironBusmePlatformLoginManager *)outer$;
@end

@interface ComAdironBusmePlatformLoginManager_DriverFailureLoginContinuation : ComAdironBusmePlatformLoginManager_LoginContinuation {
 @public
  ComAdironBusmePlatformLoginManager *this$1_;
  NSString *type_;
}

@property (nonatomic, retain) ComAdironBusmePlatformLoginManager *this$1;
@property (nonatomic, copy) NSString *type;

- (id)initWithComAdironBusmePlatformLoginManager:(ComAdironBusmePlatformLoginManager *)outer$;
- (id)initWithComAdironBusmePlatformLoginManager:(ComAdironBusmePlatformLoginManager *)outer$
                                    withNSString:(NSString *)type;
- (void)run;
@end

@interface ComAdironBusmePlatformLoginManager_PassengerSuccessLoginContinuation : ComAdironBusmePlatformLoginManager_LoginContinuation {
 @public
  ComAdironBusmePlatformLoginManager *this$1_;
}

@property (nonatomic, retain) ComAdironBusmePlatformLoginManager *this$1;

- (void)run;
- (id)initWithComAdironBusmePlatformLoginManager:(ComAdironBusmePlatformLoginManager *)outer$;
@end

@interface ComAdironBusmePlatformLoginManager_PassengerFailureLoginContinuation : ComAdironBusmePlatformLoginManager_LoginContinuation {
 @public
  ComAdironBusmePlatformLoginManager *this$1_;
  NSString *type_;
}

@property (nonatomic, retain) ComAdironBusmePlatformLoginManager *this$1;
@property (nonatomic, copy) NSString *type;

- (id)initWithComAdironBusmePlatformLoginManager:(ComAdironBusmePlatformLoginManager *)outer$;
- (id)initWithComAdironBusmePlatformLoginManager:(ComAdironBusmePlatformLoginManager *)outer$
                                    withNSString:(NSString *)type;
- (void)run;
@end

@interface ComAdironBusmePlatformLoginManager_$1 : NSObject < JavaLangRunnable > {
 @public
  ComAdironBusmePlatformLoginManager *this$0_;
  NSString *val$roleIntent_;
  ComAdironBusmePlatformLoginManager_LoginContinuation *val$success_;
  ComAdironBusmePlatformLoginManager_LoginContinuation *val$failure_;
}

@property (nonatomic, retain) ComAdironBusmePlatformLoginManager *this$0;
@property (nonatomic, copy) NSString *val$roleIntent;
@property (nonatomic, retain) ComAdironBusmePlatformLoginManager_LoginContinuation *val$success;
@property (nonatomic, retain) ComAdironBusmePlatformLoginManager_LoginContinuation *val$failure;

- (void)run;
- (id)initWithComAdironBusmePlatformLoginManager:(ComAdironBusmePlatformLoginManager *)outer$
                                    withNSString:(NSString *)capture$0
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)capture$1
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)capture$2;
@end

@interface ComAdironBusmePlatformLoginManager_$2 : NSObject < JavaLangRunnable > {
 @public
  ComAdironBusmePlatformLoginManager *this$0_;
  NSString *val$roleIntent_;
  ComAdironBusmePlatformLoginManager_LoginContinuation *val$success_;
  ComAdironBusmePlatformLoginManager_LoginContinuation *val$failure_;
}

@property (nonatomic, retain) ComAdironBusmePlatformLoginManager *this$0;
@property (nonatomic, copy) NSString *val$roleIntent;
@property (nonatomic, retain) ComAdironBusmePlatformLoginManager_LoginContinuation *val$success;
@property (nonatomic, retain) ComAdironBusmePlatformLoginManager_LoginContinuation *val$failure;

- (void)run;
- (id)initWithComAdironBusmePlatformLoginManager:(ComAdironBusmePlatformLoginManager *)outer$
                                    withNSString:(NSString *)capture$0
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)capture$1
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)capture$2;
@end

@interface ComAdironBusmePlatformLoginManager_$3 : ComAdironBusmePlatformLoginManager_LoginContinuation {
 @public
  ComAdironBusmePlatformLoginManager *this$1_;
  id<JavaUtilList> val$routes_;
}

@property (nonatomic, retain) ComAdironBusmePlatformLoginManager *this$1;
@property (nonatomic, retain) id<JavaUtilList> val$routes;

- (void)run;
- (id)initWithComAdironBusmePlatformLoginManager:(ComAdironBusmePlatformLoginManager *)outer$
                                withJavaUtilList:(id<JavaUtilList>)capture$0;
@end

@interface ComAdironBusmePlatformLoginManager_$4 : ComAdironBusmePlatformLoginManager_LoginContinuation {
 @public
  ComAdironBusmePlatformLoginManager *this$1_;
}

@property (nonatomic, retain) ComAdironBusmePlatformLoginManager *this$1;

- (void)run;
- (id)initWithComAdironBusmePlatformLoginManager:(ComAdironBusmePlatformLoginManager *)outer$;
@end

@interface ComAdironBusmePlatformLoginManager_$5 : NSObject < JavaLangRunnable > {
 @public
  ComAdironBusmePlatformLoginManager *this$0_;
  NSString *val$roleIntent_;
  ComAdironBusmePlatformLoginManager_LoginContinuation *val$success_;
  ComAdironBusmePlatformLoginManager_LoginContinuation *val$failure_;
}

@property (nonatomic, retain) ComAdironBusmePlatformLoginManager *this$0;
@property (nonatomic, copy) NSString *val$roleIntent;
@property (nonatomic, retain) ComAdironBusmePlatformLoginManager_LoginContinuation *val$success;
@property (nonatomic, retain) ComAdironBusmePlatformLoginManager_LoginContinuation *val$failure;

- (void)run;
- (id)initWithComAdironBusmePlatformLoginManager:(ComAdironBusmePlatformLoginManager *)outer$
                                    withNSString:(NSString *)capture$0
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)capture$1
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)capture$2;
@end

@interface ComAdironBusmePlatformLoginManager_$6 : NSObject < JavaLangRunnable > {
 @public
  ComAdironBusmePlatformLoginManager *this$0_;
  NSString *val$url_;
  NSString *val$roleIntent_;
  NSString *val$email_;
  NSString *val$password_;
  ComAdironBusmePlatformLoginManager_LoginContinuation *val$success_;
  ComAdironBusmePlatformLoginManager_LoginContinuation *val$failure_;
}

@property (nonatomic, retain) ComAdironBusmePlatformLoginManager *this$0;
@property (nonatomic, copy) NSString *val$url;
@property (nonatomic, copy) NSString *val$roleIntent;
@property (nonatomic, copy) NSString *val$email;
@property (nonatomic, copy) NSString *val$password;
@property (nonatomic, retain) ComAdironBusmePlatformLoginManager_LoginContinuation *val$success;
@property (nonatomic, retain) ComAdironBusmePlatformLoginManager_LoginContinuation *val$failure;

- (void)run;
- (id)initWithComAdironBusmePlatformLoginManager:(ComAdironBusmePlatformLoginManager *)outer$
                                    withNSString:(NSString *)capture$0
                                    withNSString:(NSString *)capture$1
                                    withNSString:(NSString *)capture$2
                                    withNSString:(NSString *)capture$3
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)capture$4
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)capture$5;
@end

@interface ComAdironBusmePlatformLoginManager_$7 : NSObject < JavaLangRunnable > {
 @public
  ComAdironBusmePlatformLoginManager *this$0_;
  NSString *val$url_;
  NSString *val$roleIntent_;
  NSString *val$email_;
  NSString *val$password_;
  NSString *val$driverAuthCode_;
  ComAdironBusmePlatformLoginManager_LoginContinuation *val$success_;
  ComAdironBusmePlatformLoginManager_LoginContinuation *val$failure_;
}

@property (nonatomic, retain) ComAdironBusmePlatformLoginManager *this$0;
@property (nonatomic, copy) NSString *val$url;
@property (nonatomic, copy) NSString *val$roleIntent;
@property (nonatomic, copy) NSString *val$email;
@property (nonatomic, copy) NSString *val$password;
@property (nonatomic, copy) NSString *val$driverAuthCode;
@property (nonatomic, retain) ComAdironBusmePlatformLoginManager_LoginContinuation *val$success;
@property (nonatomic, retain) ComAdironBusmePlatformLoginManager_LoginContinuation *val$failure;

- (void)run;
- (id)initWithComAdironBusmePlatformLoginManager:(ComAdironBusmePlatformLoginManager *)outer$
                                    withNSString:(NSString *)capture$0
                                    withNSString:(NSString *)capture$1
                                    withNSString:(NSString *)capture$2
                                    withNSString:(NSString *)capture$3
                                    withNSString:(NSString *)capture$4
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)capture$5
withComAdironBusmePlatformLoginManager_LoginContinuation:(ComAdironBusmePlatformLoginManager_LoginContinuation *)capture$6;
@end

@interface ComAdironBusmePlatformLoginManager_$8 : NSObject < JavaLangRunnable > {
 @public
  ComAdironBusmePlatformLoginManager *this$0_;
}

@property (nonatomic, retain) ComAdironBusmePlatformLoginManager *this$0;

- (void)run;
- (id)initWithComAdironBusmePlatformLoginManager:(ComAdironBusmePlatformLoginManager *)outer$;
@end
