//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/MarkersRequestProcessor.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmeApiAPIBase_Tag;
@class ComAdironBusmePlatformMarkerBasket;
@protocol ComAdironBusmePlatformMarkersRequestProcessor_OnMarkersResponseListener;
@protocol JavaUtilList;
@protocol JavaUtilMap;

#import "JreEmulation.h"
#import "com/adiron/busme/platform/RequestUpdater.h"

@interface ComAdironBusmePlatformMarkersRequestProcessor : NSObject < ComAdironBusmePlatformRequestUpdater_ArgumentsPreparer, ComAdironBusmePlatformRequestUpdater_ResponseProcessor > {
 @public
  ComAdironBusmePlatformMarkerBasket *markerBasket_;
  id<ComAdironBusmePlatformMarkersRequestProcessor_OnMarkersResponseListener> responseListener_;
}

@property (nonatomic, retain) ComAdironBusmePlatformMarkerBasket *markerBasket;
@property (nonatomic, retain) id<ComAdironBusmePlatformMarkersRequestProcessor_OnMarkersResponseListener> responseListener;

+ (NSString *)LOGTAG;
- (id)init;
- (id)initWithComAdironBusmePlatformMarkerBasket:(ComAdironBusmePlatformMarkerBasket *)markerBasket
withComAdironBusmePlatformMarkersRequestProcessor_OnMarkersResponseListener:(id<ComAdironBusmePlatformMarkersRequestProcessor_OnMarkersResponseListener>)responseListener;
- (ComAdironBusmePlatformMarkerBasket *)getMarkerBasket;
- (void)setMarkerBasketWithComAdironBusmePlatformMarkerBasket:(ComAdironBusmePlatformMarkerBasket *)markerBasket;
- (id<ComAdironBusmePlatformMarkersRequestProcessor_OnMarkersResponseListener>)getResponseListener;
- (void)setResponseListenerWithComAdironBusmePlatformMarkersRequestProcessor_OnMarkersResponseListener:(id<ComAdironBusmePlatformMarkersRequestProcessor_OnMarkersResponseListener>)responseListener;
- (void)processResponseWithComAdironBusmeApiAPIBase_Tag:(ComAdironBusmeApiAPIBase_Tag *)response;
- (id<JavaUtilList>)getArguments;
@end

@protocol ComAdironBusmePlatformMarkersRequestProcessor_OnMarkersResponseListener < NSObject >
- (void)onResponseWithJavaUtilMap:(id<JavaUtilMap>)response;
@end
