//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/NewGetResponseProcessor.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmeApiAPIBase_Tag;
@class ComAdironBusmePlatformActivityAPI;

#import "JreEmulation.h"
#import "com/adiron/busme/platform/RequestUpdater.h"
#import "java/lang/Runnable.h"

@interface ComAdironBusmePlatformNewGetResponseProcessor : NSObject < ComAdironBusmePlatformRequestUpdater_ResponseProcessor > {
 @public
  ComAdironBusmePlatformActivityAPI *activityAPI_;
}

@property (nonatomic, retain) ComAdironBusmePlatformActivityAPI *activityAPI;

+ (NSString *)LOGTAG;
- (id)initWithComAdironBusmePlatformActivityAPI:(ComAdironBusmePlatformActivityAPI *)api;
- (void)processResponseWithComAdironBusmeApiAPIBase_Tag:(ComAdironBusmeApiAPIBase_Tag *)response;
@end

@interface ComAdironBusmePlatformNewGetResponseProcessor_$1 : NSObject < JavaLangRunnable > {
 @public
  ComAdironBusmePlatformNewGetResponseProcessor *this$0_;
}

@property (nonatomic, retain) ComAdironBusmePlatformNewGetResponseProcessor *this$0;

- (void)run;
- (id)initWithComAdironBusmePlatformNewGetResponseProcessor:(ComAdironBusmePlatformNewGetResponseProcessor *)outer$;
@end
