//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/OnLocatorSelectedListener.java
//
//  Created by polar on 5/25/13.
//

void ComAdironBusmePlatformOnLocatorSelectedListener_unused() {}
