//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/RatesRequestProcessor.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/api/APIBase.h"
#import "com/adiron/busme/platform/ActivityAPI.h"
#import "com/adiron/busme/platform/RatesRequestProcessor.h"
#import "java/lang/Double.h"
#import "java/lang/Exception.h"
#import "java/lang/Integer.h"
#import "java/util/Map.h"

@implementation ComAdironBusmePlatformRatesRequestProcessor

- (ComAdironBusmePlatformActivityAPI *)activityAPI {
  return activityAPI_;
}
- (void)setActivityAPI:(ComAdironBusmePlatformActivityAPI *)activityAPI {
  JreOperatorRetainedAssign(&activityAPI_, activityAPI);
}
@synthesize activityAPI = activityAPI_;

- (id)initWithComAdironBusmePlatformActivityAPI:(ComAdironBusmePlatformActivityAPI *)api {
  if ((self = [super init])) {
    self.activityAPI = api;
  }
  return self;
}

- (void)processResponseWithComAdironBusmeApiAPIBase_Tag:(ComAdironBusmeApiAPIBase_Tag *)response {
  if (response != nil) {
    [self setUpdateRateWithNSString:((NSString *) [((id<JavaUtilMap>) NIL_CHK(response.attributes)) getWithId:@"updateRate"])];
    [self setSyncRateWithNSString:((NSString *) [((id<JavaUtilMap>) NIL_CHK(response.attributes)) getWithId:@"syncRate"])];
    [self setBannerRefreshRateWithNSString:((NSString *) [((id<JavaUtilMap>) NIL_CHK(response.attributes)) getWithId:@"bannerRefreshRate"])];
    [self setPostLocTimeRateWithNSString:((NSString *) [((id<JavaUtilMap>) NIL_CHK(response.attributes)) getWithId:@"postloc_time_rate"])];
    [self setPostLocDistRateWithNSString:((NSString *) [((id<JavaUtilMap>) NIL_CHK(response.attributes)) getWithId:@"postloc_dist_rate"])];
    [self setOffRouteCountThresholdWithNSString:((NSString *) [((id<JavaUtilMap>) NIL_CHK(response.attributes)) getWithId:@"offRouteCountThreshold"])];
    [self setOffRouteDistanceThresholdWithNSString:((NSString *) [((id<JavaUtilMap>) NIL_CHK(response.attributes)) getWithId:@"offRouteDistanceThreshold"])];
    [self setOffRouteTimeThresholdWithNSString:((NSString *) [((id<JavaUtilMap>) NIL_CHK(response.attributes)) getWithId:@"offRouteTimeThreshold"])];
    [self setActiveStartDisplayThresholdWithNSString:((NSString *) [((id<JavaUtilMap>) NIL_CHK(response.attributes)) getWithId:@"activeStartDisplayThreshold"])];
    [self setActiveEndWaitThresholdWithNSString:((NSString *) [((id<JavaUtilMap>) NIL_CHK(response.attributes)) getWithId:@"activeEndWaitThreshold"])];
  }
}

- (void)setActiveEndWaitThresholdWithNSString:(NSString *)rate {
  @try {
    if (rate != nil) {
      [((ComAdironBusmePlatformActivityAPI *) NIL_CHK(activityAPI_)) setActiveEndWaitThresholdWithInt:[JavaLangInteger parseIntWithNSString:rate]];
    }
  }
  @catch (JavaLangException *e) {
  }
}

- (void)setActiveStartDisplayThresholdWithNSString:(NSString *)rate {
  @try {
    if (rate != nil) {
      [((ComAdironBusmePlatformActivityAPI *) NIL_CHK(activityAPI_)) setActiveStartDisplayThresholdWithInt:[JavaLangInteger parseIntWithNSString:rate]];
    }
  }
  @catch (JavaLangException *e) {
  }
}

- (void)setOffRouteCountThresholdWithNSString:(NSString *)rate {
  @try {
    if (rate != nil) {
      [((ComAdironBusmePlatformActivityAPI *) NIL_CHK(activityAPI_)) setOffRouteCountThresholdWithInt:[JavaLangInteger parseIntWithNSString:rate]];
    }
  }
  @catch (JavaLangException *e) {
  }
}

- (void)setOffRouteTimeThresholdWithNSString:(NSString *)rate {
  @try {
    if (rate != nil) {
      [((ComAdironBusmePlatformActivityAPI *) NIL_CHK(activityAPI_)) setOffRouteTimeThresholdWithDouble:[JavaLangDouble parseDoubleWithNSString:rate]];
    }
  }
  @catch (JavaLangException *e) {
  }
}

- (void)setOffRouteDistanceThresholdWithNSString:(NSString *)rate {
  @try {
    if (rate != nil) {
      [((ComAdironBusmePlatformActivityAPI *) NIL_CHK(activityAPI_)) setOffRouteDistanceThresholdWithDouble:[JavaLangDouble parseDoubleWithNSString:rate]];
    }
  }
  @catch (JavaLangException *e) {
  }
}

- (void)setPostLocTimeRateWithNSString:(NSString *)rate {
  @try {
    if (rate != nil) {
      [((ComAdironBusmePlatformActivityAPI *) NIL_CHK(activityAPI_)) setPostlocTimeRateWithInt:[JavaLangInteger parseIntWithNSString:rate]];
    }
  }
  @catch (JavaLangException *e) {
  }
}

- (void)setPostLocDistRateWithNSString:(NSString *)rate {
  @try {
    if (rate != nil) {
      [((ComAdironBusmePlatformActivityAPI *) NIL_CHK(activityAPI_)) setPostlocDistRateWithInt:[JavaLangInteger parseIntWithNSString:rate]];
    }
  }
  @catch (JavaLangException *e) {
  }
}

- (void)setUpdateRateWithNSString:(NSString *)rate {
  @try {
    if (rate != nil) {
      [((ComAdironBusmePlatformActivityAPI *) NIL_CHK(activityAPI_)) setUpdateRateWithInt:[JavaLangInteger parseIntWithNSString:rate]];
    }
  }
  @catch (JavaLangException *e) {
  }
}

- (void)setSyncRateWithNSString:(NSString *)rate {
  @try {
    if (rate != nil) {
      [((ComAdironBusmePlatformActivityAPI *) NIL_CHK(activityAPI_)) setSyncRateWithInt:[JavaLangInteger parseIntWithNSString:rate]];
    }
  }
  @catch (JavaLangException *e) {
  }
}

- (void)setBannerRefreshRateWithNSString:(NSString *)rate {
  @try {
    if (rate != nil) {
      [((ComAdironBusmePlatformActivityAPI *) NIL_CHK(activityAPI_)) setBannerRefreshRateWithLongInt:[JavaLangInteger parseIntWithNSString:rate]];
    }
  }
  @catch (JavaLangException *e) {
  }
}

- (void)dealloc {
  JreOperatorRetainedAssign(&activityAPI_, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmePlatformRatesRequestProcessor *typedCopy = (ComAdironBusmePlatformRatesRequestProcessor *) copy;
  typedCopy.activityAPI = activityAPI_;
}

@end
