//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/RatesRequestProcessor.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmeApiAPIBase_Tag;
@class ComAdironBusmePlatformActivityAPI;

#import "JreEmulation.h"
#import "com/adiron/busme/platform/RequestUpdater.h"

@interface ComAdironBusmePlatformRatesRequestProcessor : NSObject < ComAdironBusmePlatformRequestUpdater_ResponseProcessor > {
 @public
  ComAdironBusmePlatformActivityAPI *activityAPI_;
}

@property (nonatomic, retain) ComAdironBusmePlatformActivityAPI *activityAPI;

- (id)initWithComAdironBusmePlatformActivityAPI:(ComAdironBusmePlatformActivityAPI *)api;
- (void)processResponseWithComAdironBusmeApiAPIBase_Tag:(ComAdironBusmeApiAPIBase_Tag *)response;
- (void)setActiveEndWaitThresholdWithNSString:(NSString *)rate;
- (void)setActiveStartDisplayThresholdWithNSString:(NSString *)rate;
- (void)setOffRouteCountThresholdWithNSString:(NSString *)rate;
- (void)setOffRouteTimeThresholdWithNSString:(NSString *)rate;
- (void)setOffRouteDistanceThresholdWithNSString:(NSString *)rate;
- (void)setPostLocTimeRateWithNSString:(NSString *)rate;
- (void)setPostLocDistRateWithNSString:(NSString *)rate;
- (void)setUpdateRateWithNSString:(NSString *)rate;
- (void)setSyncRateWithNSString:(NSString *)rate;
- (void)setBannerRefreshRateWithNSString:(NSString *)rate;
@end
