//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/platform/RequestUpdater.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmeApiAPIBase_Tag;
@class ComAdironBusmePlatformActivityAPI;
@class ComAdironBusmePlatformHandler;
@class JavaIoIOException;
@class JavaUtilDate;
@protocol ComAdironBusmePlatformRequestUpdater_ArgumentsPreparer;
@protocol ComAdironBusmePlatformRequestUpdater_ResponseProcessor;
@protocol ComAdironBusmePlatformRequestUpdater_UpdateProgressListener;
@protocol JavaUtilList;

#import "JreEmulation.h"
#import "com/adiron/busme/platform/RequestUpdater.h"
#import "java/lang/Runnable.h"

@interface ComAdironBusmePlatformRequestUpdater : NSObject < JavaLangRunnable > {
 @public
  ComAdironBusmePlatformActivityAPI *activityAPI_;
  BOOL please_stop_;
  id<JavaUtilList> argumentPreparers_;
  id<JavaUtilList> responseProcessors_;
  NSString *requestUrl_;
  id<ComAdironBusmePlatformRequestUpdater_UpdateProgressListener> updateProgressListener_;
}

@property (nonatomic, retain) ComAdironBusmePlatformActivityAPI *activityAPI;
@property (nonatomic, assign) BOOL please_stop;
@property (nonatomic, retain) id<JavaUtilList> argumentPreparers;
@property (nonatomic, retain) id<JavaUtilList> responseProcessors;
@property (nonatomic, copy) NSString *requestUrl;
@property (nonatomic, retain) id<ComAdironBusmePlatformRequestUpdater_UpdateProgressListener> updateProgressListener;

+ (NSString *)LOGTAG;
- (ComAdironBusmePlatformHandler *)getBackgroundHandler;
- (id)initWithComAdironBusmePlatformActivityAPI:(ComAdironBusmePlatformActivityAPI *)api;
- (int)getUpdateRate;
- (void)startUpdate;
- (void)resumeUpdate;
- (void)suspendUpdate;
- (void)stopUpdate;
- (void)addArgumentPreparerWithComAdironBusmePlatformRequestUpdater_ArgumentsPreparer:(id<ComAdironBusmePlatformRequestUpdater_ArgumentsPreparer>)p;
- (void)addResponseProcessorWithComAdironBusmePlatformRequestUpdater_ResponseProcessor:(id<ComAdironBusmePlatformRequestUpdater_ResponseProcessor>)p;
- (NSString *)getRequestUrl;
- (void)setRequestUrlWithNSString:(NSString *)requestUrl;
- (id<ComAdironBusmePlatformRequestUpdater_UpdateProgressListener>)getUpdateProgressListener;
- (void)setUpdateProgressListenerWithComAdironBusmePlatformRequestUpdater_UpdateProgressListener:(id<ComAdironBusmePlatformRequestUpdater_UpdateProgressListener>)updateProgressListener;
- (void)updateWithComAdironBusmePlatformRequestUpdater_UpdateProgressListener:(id<ComAdironBusmePlatformRequestUpdater_UpdateProgressListener>)progressListener
                                                                     withBOOL:(BOOL)forced;
- (void)run;
- (void)forceUpdate;
- (void)forceUpdateWithComAdironBusmePlatformRequestUpdater_UpdateProgressListener:(id<ComAdironBusmePlatformRequestUpdater_UpdateProgressListener>)listener;
@end

@protocol ComAdironBusmePlatformRequestUpdater_ArgumentsPreparer < NSObject >
- (id<JavaUtilList>)getArguments;
@end

@protocol ComAdironBusmePlatformRequestUpdater_ResponseProcessor < NSObject >
- (void)processResponseWithComAdironBusmeApiAPIBase_Tag:(ComAdironBusmeApiAPIBase_Tag *)response;
@end

@protocol ComAdironBusmePlatformRequestUpdater_UpdateProgressListener < NSObject >
- (void)onUpdateStartWithJavaUtilDate:(JavaUtilDate *)time
                             withBOOL:(BOOL)forced;
- (void)onArgumentsStart;
- (void)onArgumentsFinishWithBOOL:(BOOL)makeRequest;
- (void)onRequestStartWithJavaUtilDate:(JavaUtilDate *)time;
- (void)onRequestIOErrorWithJavaIoIOException:(JavaIoIOException *)e;
- (void)onRequestFinishWithJavaUtilDate:(JavaUtilDate *)time;
- (void)onResponseStart;
- (void)onResponseFinish;
- (void)onUpdateFinishWithBOOL:(BOOL)madeRequest
              withJavaUtilDate:(JavaUtilDate *)time;
@end

@interface ComAdironBusmePlatformRequestUpdater_UpdateProgressListenerBase : NSObject < ComAdironBusmePlatformRequestUpdater_UpdateProgressListener > {
}

- (void)onUpdateStartWithJavaUtilDate:(JavaUtilDate *)time
                             withBOOL:(BOOL)forced;
- (void)onArgumentsStart;
- (void)onArgumentsFinishWithBOOL:(BOOL)makeRequest;
- (void)onRequestStartWithJavaUtilDate:(JavaUtilDate *)time;
- (void)onRequestIOErrorWithJavaIoIOException:(JavaIoIOException *)e;
- (void)onRequestFinishWithJavaUtilDate:(JavaUtilDate *)time;
- (void)onResponseStart;
- (void)onResponseFinish;
- (void)onUpdateFinishWithBOOL:(BOOL)madeRequest
              withJavaUtilDate:(JavaUtilDate *)time;
- (id)init;
@end

@interface ComAdironBusmePlatformRequestUpdater_$1 : NSObject < JavaLangRunnable > {
 @public
  ComAdironBusmePlatformRequestUpdater *this$0_;
  id<ComAdironBusmePlatformRequestUpdater_UpdateProgressListener> val$listener_;
}

@property (nonatomic, retain) ComAdironBusmePlatformRequestUpdater *this$0;
@property (nonatomic, retain) id<ComAdironBusmePlatformRequestUpdater_UpdateProgressListener> val$listener;

- (void)run;
- (id)initWithComAdironBusmePlatformRequestUpdater:(ComAdironBusmePlatformRequestUpdater *)outer$
withComAdironBusmePlatformRequestUpdater_UpdateProgressListener:(id<ComAdironBusmePlatformRequestUpdater_UpdateProgressListener>)capture$0;
@end
