//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/org/osmdroid/util/constants/GeoConstants.java
//
//  Created by polar on 5/25/13.
//

#import "JreEmulation.h"

#define OrgOsmdroidUtilConstantsGeoConstants_EQUATORCIRCUMFENCE 40075016
#define OrgOsmdroidUtilConstantsGeoConstants_FEET_PER_METER 3.2808399
#define OrgOsmdroidUtilConstantsGeoConstants_METERS_PER_NAUTICAL_MILE 1852.0
#define OrgOsmdroidUtilConstantsGeoConstants_METERS_PER_STATUTE_MILE 1609.344
#define OrgOsmdroidUtilConstantsGeoConstants_RADIUS_EARTH_METERS 6378137

@protocol OrgOsmdroidUtilConstantsGeoConstants < NSObject >
@end

@interface OrgOsmdroidUtilConstantsGeoConstants : NSObject {
}
+ (int)RADIUS_EARTH_METERS;
+ (double)METERS_PER_STATUTE_MILE;
+ (double)METERS_PER_NAUTICAL_MILE;
+ (double)FEET_PER_METER;
+ (int)EQUATORCIRCUMFENCE;
@end
