//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/java/util/Observable.java
//
//  Created by polar on 5/25/13.
//

@class JavaUtilVector;
@protocol JavaUtilObserver;

#import "JreEmulation.h"

@interface JavaUtilObservable : NSObject {
 @public
  BOOL changed_;
  JavaUtilVector *obs_;
}

@property (nonatomic, assign) BOOL changed;
@property (nonatomic, retain) JavaUtilVector *obs;

- (id)init;
- (void)addObserverWithJavaUtilObserver:(id<JavaUtilObserver>)o;
- (void)deleteObserverWithJavaUtilObserver:(id<JavaUtilObserver>)o;
- (void)notifyObservers;
- (void)notifyObserversWithId:(id)arg;
- (void)deleteObservers;
- (void)setChanged;
- (void)clearChanged;
- (BOOL)hasChanged;
- (int)countObservers;
@end
