//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/integration/http/Header.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/integration/http/Header.h"

@implementation ComAdironBusmeIntegrationHttpHeader

- (id)init {
  return [super init];
}

- (NSString *)getName {
  return nil;
}

- (NSString *)getValue {
  return nil;
}

- (void)dealloc {
  [super dealloc];
}

@end
