//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/integration/http/HttpResponse.java
//
//  Created by polar on 5/25/13.
//

@class ComAdironBusmeIntegrationHttpHttpEntity;
@class ComAdironBusmeIntegrationHttpStatusLine;
@class IOSObjectArray;

#import "JreEmulation.h"

@interface ComAdironBusmeIntegrationHttpHttpResponse : NSObject {
}

- (id)init;
- (IOSObjectArray *)getAllHeaders;
- (ComAdironBusmeIntegrationHttpHttpEntity *)getEntity;
- (ComAdironBusmeIntegrationHttpStatusLine *)getStatusLine;
@end
