//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/integration/http/HttpEntity.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/integration/http/HttpEntity.h"
#import "java/io/InputStream.h"

@implementation ComAdironBusmeIntegrationHttpHttpEntity

- (id)init {
  return [super init];
}

- (long long int)getContentLength {
  return 0;
}

- (void)consumeContent {
}

- (JavaIoInputStream *)getContent {
  return nil;
}

- (void)dealloc {
  [super dealloc];
}

@end
