//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/integration/http/HttpEntity.java
//
//  Created by polar on 5/25/13.
//

@class JavaIoInputStream;

#import "JreEmulation.h"

@interface ComAdironBusmeIntegrationHttpHttpEntity : NSObject {
}

- (id)init;
- (long long int)getContentLength;
- (void)consumeContent;
- (JavaIoInputStream *)getContent;
@end
