//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/integration/http/MyHttpClient.java
//
//  Created by polar on 5/25/13.
//

#import "com/adiron/busme/integration/http/HttpEntity.h"
#import "com/adiron/busme/integration/http/HttpResponse.h"
#import "com/adiron/busme/integration/http/MyHttpClient.h"
#import "java/util/List.h"

@implementation ComAdironBusmeIntegrationHttpMyHttpClient

static NSString * ComAdironBusmeIntegrationHttpMyHttpClient_LOGTAG_ = @"MyHttpClient";

- (NSString *)csrfParam {
  return csrfParam_;
}
- (void)setCsrfParam:(NSString *)csrfParam {
  JreOperatorRetainedAssign(&csrfParam_, csrfParam);
}
@synthesize csrfParam = csrfParam_;
- (NSString *)csrfToken {
  return csrfToken_;
}
- (void)setCsrfToken:(NSString *)csrfToken {
  JreOperatorRetainedAssign(&csrfToken_, csrfToken);
}
@synthesize csrfToken = csrfToken_;
- (NSString *)masterParam {
  return masterParam_;
}
- (void)setMasterParam:(NSString *)masterParam {
  JreOperatorRetainedAssign(&masterParam_, masterParam);
}
@synthesize masterParam = masterParam_;
- (NSString *)masterToken {
  return masterToken_;
}
- (void)setMasterToken:(NSString *)masterToken {
  JreOperatorRetainedAssign(&masterToken_, masterToken);
}
@synthesize masterToken = masterToken_;

+ (NSString *)LOGTAG {
  return ComAdironBusmeIntegrationHttpMyHttpClient_LOGTAG_;
}

- (id)init {
  return [super init];
}

- (ComAdironBusmeIntegrationHttpHttpResponse *)getURLResponseWithNSString:(NSString *)url {
  return nil;
}

- (ComAdironBusmeIntegrationHttpHttpEntity *)openURLWithNSString:(NSString *)url {
  return nil;
}

- (ComAdironBusmeIntegrationHttpHttpResponse *)postURLResponseWithNSString:(NSString *)url
                                                          withJavaUtilList:(id<JavaUtilList>)params {
  return nil;
}

- (ComAdironBusmeIntegrationHttpHttpEntity *)postURLWithNSString:(NSString *)url
                                                withJavaUtilList:(id<JavaUtilList>)params {
  return nil;
}

- (ComAdironBusmeIntegrationHttpHttpEntity *)postDeleteURLWithNSString:(NSString *)url {
  return nil;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&masterToken_, nil);
  JreOperatorRetainedAssign(&masterParam_, nil);
  JreOperatorRetainedAssign(&csrfToken_, nil);
  JreOperatorRetainedAssign(&csrfParam_, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  ComAdironBusmeIntegrationHttpMyHttpClient *typedCopy = (ComAdironBusmeIntegrationHttpMyHttpClient *) copy;
  typedCopy.csrfParam = csrfParam_;
  typedCopy.csrfToken = csrfToken_;
  typedCopy.masterParam = masterParam_;
  typedCopy.masterToken = masterToken_;
}

@end
