//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/src/main/java/com/adiron/busme/integration/http/StatusLine.java
//
//  Created by polar on 5/25/13.
//

#import "JreEmulation.h"

@interface ComAdironBusmeIntegrationHttpStatusLine : NSObject {
 @public
  int statusCode_;
  NSString *reasonPhrase_;
}

@property (nonatomic, assign) int statusCode;
@property (nonatomic, copy) NSString *reasonPhrase;

- (id)initWithInt:(int)code
     withNSString:(NSString *)reason;
- (int)getStatusCode;
- (NSString *)getReasonPhrase;
@end
